/* Generated by scripts/build-public-facts.mjs — 2026-09-09 */
export type PublicFactRow = {
  official: string;
  restaurants?: number;
  vets?: number;
  groomers?: number;
  salons?: number;
  stays?: number;
  shelters?: number;
  rescueDogs90?: number;
  tourSpots?: number;
};

export const PUBLIC_FACTS_UPDATED = "2026-09-09";

export const PUBLIC_FACTS: PublicFactRow[] = [
  {
    "official": "강원특별자치도 강릉시",
    "restaurants": 4682,
    "vets": 19,
    "groomers": 64,
    "stays": 80,
    "shelters": 1,
    "rescueDogs90": 89,
    "tourSpots": 48
  },
  {
    "official": "강원특별자치도 고성군",
    "restaurants": 747,
    "vets": 3,
    "groomers": 3,
    "stays": 18,
    "shelters": 1,
    "rescueDogs90": 36,
    "tourSpots": 40
  },
  {
    "official": "강원특별자치도 동해시",
    "restaurants": 1673,
    "vets": 4,
    "groomers": 28,
    "stays": 19,
    "shelters": 1,
    "rescueDogs90": 74,
    "tourSpots": 26
  },
  {
    "official": "강원특별자치도 삼척시",
    "restaurants": 1297,
    "vets": 6,
    "groomers": 7,
    "stays": 5,
    "shelters": 2,
    "rescueDogs90": 21,
    "tourSpots": 63
  },
  {
    "official": "강원특별자치도 속초시",
    "restaurants": 2410,
    "vets": 9,
    "groomers": 30,
    "stays": 36,
    "shelters": 1,
    "rescueDogs90": 23,
    "tourSpots": 32
  },
  {
    "official": "강원특별자치도 양구군",
    "restaurants": 449,
    "vets": 4,
    "groomers": 5,
    "stays": 3,
    "shelters": 1,
    "rescueDogs90": 13,
    "tourSpots": 21
  },
  {
    "official": "강원특별자치도 양양군",
    "restaurants": 939,
    "vets": 4,
    "groomers": 7,
    "stays": 24,
    "shelters": 1,
    "rescueDogs90": 23,
    "tourSpots": 64
  },
  {
    "official": "강원특별자치도 영월군",
    "restaurants": 759,
    "vets": 4,
    "groomers": 2,
    "stays": 5,
    "shelters": 1,
    "rescueDogs90": 5,
    "tourSpots": 40
  },
  {
    "official": "강원특별자치도 원주시",
    "restaurants": 6019,
    "vets": 30,
    "groomers": 112,
    "stays": 11,
    "shelters": 1,
    "rescueDogs90": 91,
    "tourSpots": 42
  },
  {
    "official": "강원특별자치도 인제군",
    "restaurants": 827,
    "vets": 5,
    "groomers": 4,
    "stays": 3,
    "shelters": 1,
    "rescueDogs90": 24,
    "tourSpots": 28
  },
  {
    "official": "강원특별자치도 정선군",
    "restaurants": 969,
    "vets": 5,
    "groomers": 1,
    "stays": 9,
    "shelters": 2,
    "rescueDogs90": 39,
    "tourSpots": 26
  },
  {
    "official": "강원특별자치도 철원군",
    "restaurants": 891,
    "vets": 7,
    "groomers": 8,
    "stays": 1,
    "shelters": 1,
    "rescueDogs90": 63,
    "tourSpots": 31
  },
  {
    "official": "강원특별자치도 춘천시",
    "restaurants": 4823,
    "vets": 30,
    "groomers": 63,
    "stays": 11,
    "shelters": 1,
    "rescueDogs90": 119,
    "tourSpots": 62
  },
  {
    "official": "강원특별자치도 태백시",
    "restaurants": 792,
    "vets": 2,
    "groomers": 12,
    "stays": 6,
    "shelters": 1,
    "rescueDogs90": 17,
    "tourSpots": 27
  },
  {
    "official": "강원특별자치도 평창군",
    "restaurants": 1239,
    "vets": 5,
    "groomers": 3,
    "stays": 25,
    "shelters": 1,
    "rescueDogs90": 15,
    "tourSpots": 60
  },
  {
    "official": "강원특별자치도 홍천군",
    "restaurants": 1507,
    "vets": 10,
    "groomers": 9,
    "stays": 14,
    "shelters": 1,
    "rescueDogs90": 22,
    "tourSpots": 33
  },
  {
    "official": "강원특별자치도 화천군",
    "restaurants": 516,
    "vets": 5,
    "shelters": 1,
    "rescueDogs90": 17,
    "tourSpots": 34
  },
  {
    "official": "강원특별자치도 횡성군",
    "restaurants": 922,
    "vets": 16,
    "groomers": 5,
    "stays": 5,
    "shelters": 1,
    "rescueDogs90": 22,
    "tourSpots": 11
  },
  {
    "official": "경기도 가평군",
    "restaurants": 1754,
    "vets": 9,
    "groomers": 11,
    "stays": 74,
    "shelters": 1,
    "rescueDogs90": 29,
    "tourSpots": 48
  },
  {
    "official": "경기도 고양시",
    "restaurants": 9615,
    "vets": 121,
    "groomers": 245,
    "stays": 8,
    "shelters": 1,
    "rescueDogs90": 106,
    "tourSpots": 30
  },
  {
    "official": "경기도 고양시 덕양구 삼송동",
    "restaurants": 218,
    "vets": 7,
    "groomers": 10
  },
  {
    "official": "경기도 고양시 덕양구 원흥동",
    "restaurants": 232,
    "vets": 2,
    "groomers": 5,
    "stays": 2
  },
  {
    "official": "경기도 고양시 덕양구 지축동",
    "restaurants": 178,
    "vets": 2,
    "groomers": 6
  },
  {
    "official": "경기도 고양시 덕양구 토당동",
    "restaurants": 190,
    "vets": 3,
    "groomers": 3
  },
  {
    "official": "경기도 고양시 덕양구 행신동",
    "restaurants": 546,
    "vets": 8,
    "groomers": 13
  },
  {
    "official": "경기도 고양시 덕양구 화정동",
    "restaurants": 598,
    "vets": 7,
    "groomers": 10
  },
  {
    "official": "경기도 고양시 일산",
    "restaurants": 5404,
    "vets": 74,
    "groomers": 142,
    "stays": 6
  },
  {
    "official": "경기도 고양시 일산동구 마두동",
    "restaurants": 303,
    "vets": 6,
    "groomers": 9
  },
  {
    "official": "경기도 고양시 일산동구 백석동",
    "restaurants": 682,
    "vets": 7,
    "groomers": 20
  },
  {
    "official": "경기도 고양시 일산동구 식사동",
    "restaurants": 247,
    "vets": 7,
    "groomers": 9
  },
  {
    "official": "경기도 고양시 일산동구 정발산동",
    "restaurants": 466,
    "vets": 5,
    "groomers": 14
  },
  {
    "official": "경기도 고양시 일산서구 대화동",
    "restaurants": 753,
    "vets": 11,
    "groomers": 15
  },
  {
    "official": "경기도 고양시 일산서구 주엽동",
    "restaurants": 247,
    "vets": 6,
    "groomers": 10
  },
  {
    "official": "경기도 고양시 일산서구 탄현동",
    "restaurants": 250,
    "vets": 4,
    "groomers": 8
  },
  {
    "official": "경기도 과천시",
    "restaurants": 588,
    "vets": 13,
    "groomers": 9,
    "rescueDogs90": 6,
    "tourSpots": 15
  },
  {
    "official": "경기도 광명시",
    "restaurants": 2433,
    "vets": 21,
    "groomers": 50,
    "stays": 3,
    "shelters": 1,
    "rescueDogs90": 42,
    "tourSpots": 5
  },
  {
    "official": "경기도 광명시 소하동",
    "restaurants": 422,
    "vets": 5,
    "groomers": 14
  },
  {
    "official": "경기도 광명시 일직동",
    "restaurants": 408,
    "vets": 2,
    "groomers": 7,
    "stays": 2
  },
  {
    "official": "경기도 광명시 철산동",
    "restaurants": 390,
    "vets": 8,
    "groomers": 7,
    "stays": 1
  },
  {
    "official": "경기도 광명시 하안동",
    "restaurants": 430,
    "vets": 3,
    "groomers": 4
  },
  {
    "official": "경기도 광주시",
    "restaurants": 3732,
    "vets": 36,
    "groomers": 102,
    "stays": 2,
    "shelters": 1,
    "rescueDogs90": 118,
    "tourSpots": 36
  },
  {
    "official": "경기도 광주시 경안동",
    "restaurants": 408,
    "vets": 6,
    "groomers": 10
  },
  {
    "official": "경기도 광주시 곤지암읍",
    "restaurants": 423,
    "vets": 5,
    "groomers": 5,
    "stays": 1
  },
  {
    "official": "경기도 광주시 초월읍",
    "restaurants": 369,
    "vets": 4,
    "groomers": 13,
    "shelters": 1
  },
  {
    "official": "경기도 광주시 태전동",
    "restaurants": 200,
    "vets": 3,
    "groomers": 7
  },
  {
    "official": "경기도 구리시",
    "restaurants": 2151,
    "vets": 16,
    "groomers": 54,
    "shelters": 1,
    "rescueDogs90": 18,
    "tourSpots": 4
  },
  {
    "official": "경기도 구리시 갈매동",
    "restaurants": 328,
    "groomers": 14
  },
  {
    "official": "경기도 구리시 교문동",
    "restaurants": 304,
    "vets": 3,
    "groomers": 10
  },
  {
    "official": "경기도 구리시 인창동",
    "restaurants": 361,
    "vets": 4,
    "groomers": 13
  },
  {
    "official": "경기도 군포시",
    "restaurants": 2245,
    "vets": 14,
    "groomers": 41,
    "stays": 1,
    "rescueDogs90": 7,
    "tourSpots": 3
  },
  {
    "official": "경기도 군포시 금정동",
    "restaurants": 383,
    "vets": 2,
    "groomers": 9,
    "stays": 1
  },
  {
    "official": "경기도 군포시 산본동",
    "restaurants": 914,
    "vets": 8,
    "groomers": 13
  },
  {
    "official": "경기도 김포시",
    "restaurants": 4798,
    "vets": 51,
    "groomers": 153,
    "stays": 11,
    "shelters": 3,
    "rescueDogs90": 91,
    "tourSpots": 29
  },
  {
    "official": "경기도 김포시 고촌읍",
    "restaurants": 332,
    "vets": 4,
    "groomers": 11,
    "stays": 2
  },
  {
    "official": "경기도 김포시 구래동",
    "restaurants": 690,
    "vets": 4,
    "groomers": 24,
    "stays": 2
  },
  {
    "official": "경기도 김포시 사우동",
    "restaurants": 313,
    "vets": 3,
    "groomers": 7
  },
  {
    "official": "경기도 김포시 운양동",
    "restaurants": 288,
    "vets": 6,
    "groomers": 16
  },
  {
    "official": "경기도 김포시 장기동",
    "restaurants": 625,
    "vets": 11,
    "groomers": 32,
    "stays": 5
  },
  {
    "official": "경기도 김포시 풍무동",
    "restaurants": 394,
    "vets": 6,
    "groomers": 20
  },
  {
    "official": "경기도 남양주시",
    "restaurants": 7137,
    "vets": 71,
    "groomers": 203,
    "stays": 6,
    "shelters": 1,
    "rescueDogs90": 125,
    "tourSpots": 27
  },
  {
    "official": "경기도 남양주시 다산동",
    "restaurants": 1227,
    "vets": 15,
    "groomers": 55
  },
  {
    "official": "경기도 남양주시 별내동",
    "restaurants": 849,
    "vets": 10,
    "groomers": 34,
    "stays": 1
  },
  {
    "official": "경기도 남양주시 오남읍",
    "restaurants": 518,
    "vets": 4,
    "groomers": 14
  },
  {
    "official": "경기도 남양주시 와부읍",
    "restaurants": 544,
    "vets": 5,
    "groomers": 11
  },
  {
    "official": "경기도 남양주시 진접읍",
    "restaurants": 951,
    "vets": 8,
    "groomers": 22,
    "stays": 1
  },
  {
    "official": "경기도 남양주시 퇴계원읍",
    "restaurants": 193,
    "vets": 4,
    "groomers": 5,
    "shelters": 1
  },
  {
    "official": "경기도 남양주시 평내동",
    "restaurants": 274,
    "vets": 3,
    "groomers": 10
  },
  {
    "official": "경기도 남양주시 호평동",
    "restaurants": 442,
    "vets": 4,
    "groomers": 14
  },
  {
    "official": "경기도 남양주시 화도읍",
    "restaurants": 1189,
    "vets": 9,
    "groomers": 27,
    "stays": 2
  },
  {
    "official": "경기도 동두천시",
    "restaurants": 1220,
    "vets": 10,
    "groomers": 25,
    "rescueDogs90": 29,
    "tourSpots": 7
  },
  {
    "official": "경기도 부천시",
    "restaurants": 7891,
    "vets": 70,
    "groomers": 184,
    "stays": 5,
    "shelters": 4,
    "rescueDogs90": 61,
    "tourSpots": 13
  },
  {
    "official": "경기도 성남시",
    "restaurants": 9003,
    "vets": 117,
    "groomers": 172,
    "stays": 16,
    "rescueDogs90": 104,
    "tourSpots": 34
  },
  {
    "official": "경기도 성남시 분당구",
    "restaurants": 4479,
    "vets": 72,
    "groomers": 89,
    "stays": 11,
    "shelters": 1
  },
  {
    "official": "경기도 성남시 분당구 구미동",
    "restaurants": 405,
    "vets": 9,
    "groomers": 7,
    "stays": 1
  },
  {
    "official": "경기도 성남시 분당구 백현동",
    "restaurants": 296,
    "vets": 6,
    "groomers": 9,
    "stays": 1
  },
  {
    "official": "경기도 성남시 분당구 삼평동",
    "restaurants": 539,
    "vets": 1,
    "groomers": 2,
    "stays": 2
  },
  {
    "official": "경기도 성남시 분당구 서현동",
    "restaurants": 666,
    "vets": 8,
    "groomers": 11,
    "stays": 5
  },
  {
    "official": "경기도 성남시 분당구 수내동",
    "restaurants": 415,
    "vets": 6,
    "groomers": 6
  },
  {
    "official": "경기도 성남시 분당구 야탑동",
    "restaurants": 612,
    "vets": 8,
    "groomers": 11
  },
  {
    "official": "경기도 성남시 분당구 운중동",
    "restaurants": 148,
    "vets": 3,
    "groomers": 6
  },
  {
    "official": "경기도 성남시 분당구 이매동",
    "restaurants": 92,
    "vets": 4,
    "groomers": 5
  },
  {
    "official": "경기도 성남시 분당구 정자동",
    "restaurants": 841,
    "vets": 16,
    "groomers": 12,
    "stays": 2
  },
  {
    "official": "경기도 성남시 분당구 판교동",
    "restaurants": 114,
    "vets": 5,
    "groomers": 6
  },
  {
    "official": "경기도 성남시 수정구 복정동",
    "restaurants": 126,
    "vets": 1,
    "groomers": 1
  },
  {
    "official": "경기도 성남시 수정구 태평동",
    "restaurants": 477,
    "vets": 3,
    "groomers": 8
  },
  {
    "official": "경기도 성남시 중원구 상대원동",
    "restaurants": 475,
    "vets": 2,
    "groomers": 5
  },
  {
    "official": "경기도 성남시 중원구 성남동",
    "restaurants": 785,
    "vets": 5,
    "groomers": 11,
    "stays": 2
  },
  {
    "official": "경기도 수원시",
    "restaurants": 12533,
    "vets": 123,
    "groomers": 295,
    "stays": 33,
    "shelters": 1,
    "rescueDogs90": 89,
    "tourSpots": 39
  },
  {
    "official": "경기도 수원시 권선구 권선동",
    "restaurants": 822,
    "vets": 9,
    "groomers": 22,
    "stays": 2
  },
  {
    "official": "경기도 수원시 권선구 세류동",
    "restaurants": 441,
    "vets": 3,
    "groomers": 15
  },
  {
    "official": "경기도 수원시 권선구 호매실동",
    "restaurants": 228,
    "vets": 4,
    "groomers": 9
  },
  {
    "official": "경기도 수원시 영통구 망포동",
    "restaurants": 221,
    "vets": 8,
    "groomers": 8
  },
  {
    "official": "경기도 수원시 영통구 매탄동",
    "restaurants": 796,
    "vets": 5,
    "groomers": 19
  },
  {
    "official": "경기도 수원시 영통구 영통동",
    "restaurants": 921,
    "vets": 10,
    "groomers": 12,
    "stays": 2
  },
  {
    "official": "경기도 수원시 영통구 원천동",
    "restaurants": 384,
    "vets": 5,
    "groomers": 14
  },
  {
    "official": "경기도 수원시 영통구 이의동",
    "restaurants": 555,
    "vets": 12,
    "groomers": 23
  },
  {
    "official": "경기도 수원시 팔달구 인계동",
    "restaurants": 1134,
    "vets": 10,
    "groomers": 24,
    "stays": 7
  },
  {
    "official": "경기도 수원시 팔달구 화서동",
    "restaurants": 372,
    "vets": 4,
    "groomers": 11
  },
  {
    "official": "경기도 시흥시",
    "restaurants": 5828,
    "vets": 39,
    "groomers": 130,
    "stays": 6,
    "shelters": 1,
    "rescueDogs90": 84,
    "tourSpots": 18
  },
  {
    "official": "경기도 시흥시 대야동",
    "restaurants": 481,
    "vets": 4,
    "groomers": 10
  },
  {
    "official": "경기도 시흥시 목감동",
    "restaurants": 86,
    "groomers": 1
  },
  {
    "official": "경기도 시흥시 배곧동",
    "restaurants": 559,
    "vets": 6,
    "groomers": 35
  },
  {
    "official": "경기도 시흥시 월곶동",
    "restaurants": 188,
    "vets": 2,
    "groomers": 4
  },
  {
    "official": "경기도 시흥시 은행동",
    "restaurants": 385,
    "vets": 6,
    "groomers": 15
  },
  {
    "official": "경기도 시흥시 정왕동",
    "restaurants": 2210,
    "vets": 9,
    "groomers": 25,
    "stays": 6
  },
  {
    "official": "경기도 시흥시 하중동",
    "restaurants": 61,
    "groomers": 1
  },
  {
    "official": "경기도 안산시",
    "restaurants": 7611,
    "vets": 39,
    "groomers": 145,
    "stays": 12,
    "shelters": 6,
    "rescueDogs90": 116,
    "tourSpots": 39
  },
  {
    "official": "경기도 안산시 단원구 고잔동",
    "restaurants": 1768,
    "vets": 11,
    "groomers": 29,
    "stays": 1
  },
  {
    "official": "경기도 안산시 단원구 선부동",
    "restaurants": 676,
    "vets": 3,
    "groomers": 10
  },
  {
    "official": "경기도 안산시 단원구 초지동",
    "restaurants": 309,
    "vets": 3,
    "groomers": 12
  },
  {
    "official": "경기도 안산시 상록구 건건동",
    "restaurants": 120,
    "vets": 1,
    "groomers": 2
  },
  {
    "official": "경기도 안산시 상록구 본오동",
    "restaurants": 807,
    "vets": 5,
    "groomers": 17
  },
  {
    "official": "경기도 안산시 상록구 사동",
    "restaurants": 713,
    "vets": 2,
    "groomers": 8,
    "stays": 1
  },
  {
    "official": "경기도 안산시 상록구 월피동",
    "restaurants": 326,
    "vets": 2,
    "groomers": 12
  },
  {
    "official": "경기도 안성시",
    "restaurants": 3146,
    "vets": 35,
    "groomers": 32,
    "stays": 3,
    "shelters": 1,
    "rescueDogs90": 101,
    "tourSpots": 54
  },
  {
    "official": "경기도 안성시 공도읍",
    "restaurants": 602,
    "vets": 9,
    "groomers": 17
  },
  {
    "official": "경기도 안양시",
    "restaurants": 5468,
    "vets": 53,
    "groomers": 97,
    "stays": 7,
    "rescueDogs90": 20,
    "tourSpots": 13
  },
  {
    "official": "경기도 안양시 동안구 관양동",
    "restaurants": 1319,
    "vets": 13,
    "groomers": 13,
    "stays": 2
  },
  {
    "official": "경기도 안양시 동안구 평촌동",
    "restaurants": 362,
    "vets": 9,
    "groomers": 9
  },
  {
    "official": "경기도 안양시 동안구 호계동",
    "restaurants": 980,
    "vets": 7,
    "groomers": 17,
    "stays": 2
  },
  {
    "official": "경기도 안양시 만안구 박달동",
    "restaurants": 278,
    "vets": 1,
    "groomers": 7
  },
  {
    "official": "경기도 안양시 만안구 석수동",
    "restaurants": 370,
    "vets": 2,
    "groomers": 11
  },
  {
    "official": "경기도 양주시",
    "restaurants": 3142,
    "vets": 25,
    "groomers": 87,
    "stays": 2,
    "shelters": 29,
    "rescueDogs90": 86,
    "tourSpots": 30
  },
  {
    "official": "경기도 양주시 고읍동",
    "restaurants": 46,
    "vets": 1,
    "groomers": 2
  },
  {
    "official": "경기도 양주시 덕계동",
    "restaurants": 288,
    "vets": 2,
    "groomers": 12
  },
  {
    "official": "경기도 양주시 옥정동",
    "restaurants": 666,
    "vets": 5,
    "groomers": 30,
    "stays": 1
  },
  {
    "official": "경기도 양주시 회정동",
    "restaurants": 62,
    "groomers": 1
  },
  {
    "official": "경기도 양평군",
    "restaurants": 1880,
    "vets": 17,
    "groomers": 22,
    "stays": 6,
    "shelters": 1,
    "rescueDogs90": 101,
    "tourSpots": 45
  },
  {
    "official": "경기도 여주시",
    "restaurants": 2010,
    "vets": 16,
    "groomers": 22,
    "stays": 3,
    "shelters": 1,
    "rescueDogs90": 104,
    "tourSpots": 33
  },
  {
    "official": "경기도 연천군",
    "restaurants": 860,
    "vets": 7,
    "groomers": 5,
    "stays": 1,
    "rescueDogs90": 77,
    "tourSpots": 26
  },
  {
    "official": "경기도 오산시",
    "restaurants": 2482,
    "vets": 19,
    "groomers": 51,
    "stays": 1,
    "shelters": 1,
    "rescueDogs90": 36,
    "tourSpots": 13
  },
  {
    "official": "경기도 오산시 세교동",
    "restaurants": 116,
    "groomers": 2
  },
  {
    "official": "경기도 용인시",
    "restaurants": 8694,
    "vets": 120,
    "groomers": 230,
    "stays": 17,
    "shelters": 1,
    "rescueDogs90": 88,
    "tourSpots": 62
  },
  {
    "official": "경기도 용인시 기흥구",
    "restaurants": 3037,
    "vets": 45,
    "groomers": 91,
    "stays": 7
  },
  {
    "official": "경기도 용인시 기흥구 구갈동",
    "restaurants": 465,
    "vets": 5,
    "groomers": 10
  },
  {
    "official": "경기도 용인시 기흥구 동백동",
    "restaurants": 144,
    "vets": 3,
    "groomers": 5
  },
  {
    "official": "경기도 용인시 기흥구 마북동",
    "restaurants": 143,
    "vets": 4,
    "groomers": 4
  },
  {
    "official": "경기도 용인시 기흥구 보정동",
    "restaurants": 317,
    "vets": 7,
    "groomers": 10
  },
  {
    "official": "경기도 용인시 기흥구 상갈동",
    "restaurants": 91,
    "vets": 1,
    "groomers": 2
  },
  {
    "official": "경기도 용인시 기흥구 서천동",
    "restaurants": 97,
    "vets": 2,
    "groomers": 5
  },
  {
    "official": "경기도 용인시 기흥구 신갈동",
    "restaurants": 230,
    "vets": 5,
    "groomers": 9,
    "stays": 2
  },
  {
    "official": "경기도 용인시 기흥구 영덕동",
    "restaurants": 298,
    "vets": 4,
    "groomers": 11
  },
  {
    "official": "경기도 용인시 기흥구 청덕동",
    "restaurants": 60,
    "vets": 1,
    "groomers": 2
  },
  {
    "official": "경기도 용인시 수지구",
    "restaurants": 1984,
    "vets": 44,
    "groomers": 72,
    "stays": 2
  },
  {
    "official": "경기도 용인시 수지구 동천동",
    "restaurants": 262,
    "vets": 5,
    "groomers": 12
  },
  {
    "official": "경기도 용인시 수지구 상현동",
    "restaurants": 304,
    "vets": 9,
    "groomers": 15
  },
  {
    "official": "경기도 용인시 수지구 성복동",
    "restaurants": 230,
    "vets": 8,
    "groomers": 11
  },
  {
    "official": "경기도 용인시 수지구 신봉동",
    "restaurants": 189,
    "vets": 6,
    "groomers": 8
  },
  {
    "official": "경기도 용인시 수지구 죽전동",
    "restaurants": 410,
    "vets": 9,
    "groomers": 14
  },
  {
    "official": "경기도 용인시 수지구 풍덕천동",
    "restaurants": 508,
    "vets": 7,
    "groomers": 10,
    "stays": 2
  },
  {
    "official": "경기도 용인시 처인구 김량장동",
    "restaurants": 498,
    "vets": 3,
    "groomers": 6,
    "stays": 1
  },
  {
    "official": "경기도 용인시 처인구 모현읍",
    "restaurants": 349,
    "vets": 1,
    "groomers": 13
  },
  {
    "official": "경기도 용인시 처인구 역북동",
    "restaurants": 449,
    "vets": 4,
    "groomers": 10
  },
  {
    "official": "경기도 용인시 처인구 포곡읍",
    "restaurants": 530,
    "vets": 5,
    "groomers": 8,
    "stays": 2
  },
  {
    "official": "경기도 의왕시",
    "restaurants": 1142,
    "vets": 13,
    "groomers": 24,
    "stays": 2,
    "shelters": 1,
    "rescueDogs90": 13,
    "tourSpots": 8
  },
  {
    "official": "경기도 의왕시 내손동",
    "restaurants": 245,
    "vets": 5,
    "groomers": 8
  },
  {
    "official": "경기도 의정부시",
    "restaurants": 4832,
    "vets": 32,
    "groomers": 140,
    "stays": 3,
    "rescueDogs90": 41,
    "tourSpots": 7
  },
  {
    "official": "경기도 의정부시 가능동",
    "restaurants": 517,
    "vets": 2,
    "groomers": 11
  },
  {
    "official": "경기도 의정부시 녹양동",
    "restaurants": 145,
    "vets": 2,
    "groomers": 7
  },
  {
    "official": "경기도 의정부시 민락동",
    "restaurants": 692,
    "vets": 6,
    "groomers": 29
  },
  {
    "official": "경기도 의정부시 장암동",
    "restaurants": 91,
    "vets": 1,
    "groomers": 3,
    "stays": 1
  },
  {
    "official": "경기도 의정부시 호원동",
    "restaurants": 438,
    "vets": 4,
    "groomers": 18
  },
  {
    "official": "경기도 이천시",
    "restaurants": 3145,
    "vets": 35,
    "groomers": 41,
    "stays": 3,
    "rescueDogs90": 89,
    "tourSpots": 29
  },
  {
    "official": "경기도 파주시",
    "restaurants": 5769,
    "vets": 54,
    "groomers": 136,
    "stays": 15,
    "shelters": 1,
    "rescueDogs90": 131,
    "tourSpots": 48
  },
  {
    "official": "경기도 파주시 교하동",
    "restaurants": 24,
    "groomers": 1
  },
  {
    "official": "경기도 파주시 금촌동",
    "restaurants": 749,
    "vets": 7,
    "groomers": 13
  },
  {
    "official": "경기도 파주시 문산읍",
    "restaurants": 669,
    "vets": 3,
    "groomers": 12,
    "stays": 1
  },
  {
    "official": "경기도 파주시 야당동",
    "restaurants": 503,
    "vets": 6,
    "groomers": 14,
    "stays": 1
  },
  {
    "official": "경기도 파주시 탄현면",
    "restaurants": 425,
    "groomers": 3,
    "stays": 11
  },
  {
    "official": "경기도 평택시",
    "restaurants": 8432,
    "vets": 61,
    "groomers": 180,
    "stays": 14,
    "shelters": 1,
    "rescueDogs90": 172,
    "tourSpots": 22
  },
  {
    "official": "경기도 평택시 고덕동",
    "restaurants": 831,
    "vets": 5,
    "groomers": 25
  },
  {
    "official": "경기도 평택시 비전동",
    "restaurants": 912,
    "vets": 8,
    "groomers": 29,
    "stays": 1
  },
  {
    "official": "경기도 평택시 안중읍",
    "restaurants": 639,
    "vets": 6,
    "groomers": 15,
    "stays": 1
  },
  {
    "official": "경기도 평택시 팽성읍",
    "restaurants": 494,
    "vets": 4,
    "groomers": 16,
    "stays": 1
  },
  {
    "official": "경기도 평택시 포승읍",
    "restaurants": 543,
    "groomers": 3,
    "stays": 1
  },
  {
    "official": "경기도 포천시",
    "restaurants": 3248,
    "vets": 22,
    "groomers": 23,
    "stays": 5,
    "rescueDogs90": 174,
    "tourSpots": 35
  },
  {
    "official": "경기도 포천시 소흘읍",
    "restaurants": 865,
    "vets": 4,
    "groomers": 11,
    "stays": 1
  },
  {
    "official": "경기도 하남시",
    "restaurants": 2911,
    "vets": 39,
    "groomers": 104,
    "stays": 2,
    "rescueDogs90": 35,
    "tourSpots": 15
  },
  {
    "official": "경기도 하남시 감일동",
    "restaurants": 81,
    "vets": 1,
    "groomers": 3
  },
  {
    "official": "경기도 하남시 덕풍동",
    "restaurants": 496,
    "vets": 5,
    "groomers": 11
  },
  {
    "official": "경기도 하남시 미사동",
    "restaurants": 43,
    "groomers": 2,
    "shelters": 1
  },
  {
    "official": "경기도 하남시 신장동",
    "restaurants": 461,
    "vets": 10,
    "groomers": 14,
    "stays": 2
  },
  {
    "official": "경기도 하남시 창우동",
    "restaurants": 77,
    "groomers": 1
  },
  {
    "official": "경기도 하남시 풍산동",
    "restaurants": 276,
    "vets": 3,
    "groomers": 9
  },
  {
    "official": "경기도 화성시",
    "restaurants": 10160,
    "vets": 101,
    "groomers": 209,
    "stays": 11,
    "rescueDogs90": 294,
    "tourSpots": 55
  },
  {
    "official": "경기도 화성시 동탄",
    "restaurants": 3640,
    "vets": 41,
    "groomers": 93,
    "stays": 1
  },
  {
    "official": "경상남도 거제시",
    "restaurants": 3981,
    "vets": 13,
    "groomers": 60,
    "stays": 23,
    "shelters": 1,
    "rescueDogs90": 73,
    "tourSpots": 57
  },
  {
    "official": "경상남도 거제시 고현동",
    "restaurants": 929,
    "vets": 6,
    "groomers": 18,
    "stays": 1
  },
  {
    "official": "경상남도 거창군",
    "restaurants": 999,
    "vets": 13,
    "groomers": 7,
    "stays": 1,
    "shelters": 1,
    "rescueDogs90": 86,
    "tourSpots": 34
  },
  {
    "official": "경상남도 고성군",
    "restaurants": 833,
    "vets": 11,
    "groomers": 4,
    "stays": 2,
    "shelters": 1,
    "rescueDogs90": 39,
    "tourSpots": 32
  },
  {
    "official": "경상남도 김해시",
    "restaurants": 7659,
    "vets": 51,
    "groomers": 152,
    "stays": 9,
    "rescueDogs90": 169,
    "tourSpots": 33
  },
  {
    "official": "경상남도 김해시 율하동",
    "restaurants": 276,
    "vets": 3,
    "groomers": 14
  },
  {
    "official": "경상남도 김해시 장유",
    "restaurants": 205,
    "vets": 2,
    "groomers": 2
  },
  {
    "official": "경상남도 김해시 진영읍",
    "restaurants": 782,
    "vets": 5,
    "groomers": 16
  },
  {
    "official": "경상남도 남해군",
    "restaurants": 922,
    "vets": 8,
    "groomers": 2,
    "stays": 12,
    "shelters": 1,
    "rescueDogs90": 49,
    "tourSpots": 51
  },
  {
    "official": "경상남도 밀양시",
    "restaurants": 1699,
    "vets": 10,
    "groomers": 13,
    "stays": 3,
    "shelters": 1,
    "rescueDogs90": 126,
    "tourSpots": 29
  },
  {
    "official": "경상남도 사천시",
    "restaurants": 1904,
    "vets": 19,
    "groomers": 24,
    "stays": 4,
    "shelters": 1,
    "rescueDogs90": 71,
    "tourSpots": 23
  },
  {
    "official": "경상남도 산청군",
    "restaurants": 606,
    "vets": 9,
    "groomers": 2,
    "stays": 1,
    "shelters": 1,
    "rescueDogs90": 22,
    "tourSpots": 59
  },
  {
    "official": "경상남도 양산시",
    "restaurants": 5208,
    "vets": 27,
    "groomers": 117,
    "stays": 4,
    "shelters": 1,
    "rescueDogs90": 35,
    "tourSpots": 22
  },
  {
    "official": "경상남도 양산시 물금읍",
    "restaurants": 1542,
    "vets": 10,
    "groomers": 50
  },
  {
    "official": "경상남도 의령군",
    "restaurants": 350,
    "vets": 5,
    "groomers": 1,
    "shelters": 1,
    "rescueDogs90": 59,
    "tourSpots": 14
  },
  {
    "official": "경상남도 진주시",
    "restaurants": 5107,
    "vets": 38,
    "groomers": 93,
    "stays": 5,
    "shelters": 1,
    "rescueDogs90": 101,
    "tourSpots": 33
  },
  {
    "official": "경상남도 진주시 충무공동",
    "restaurants": 385,
    "vets": 2,
    "groomers": 10
  },
  {
    "official": "경상남도 창녕군",
    "restaurants": 1047,
    "vets": 16,
    "groomers": 7,
    "stays": 5,
    "shelters": 1,
    "rescueDogs90": 74,
    "tourSpots": 26
  },
  {
    "official": "경상남도 창원시",
    "restaurants": 13329,
    "vets": 83,
    "groomers": 206,
    "stays": 26,
    "shelters": 2,
    "rescueDogs90": 253,
    "tourSpots": 106
  },
  {
    "official": "경상남도 창원시 마산합포구",
    "restaurants": 2926,
    "vets": 13,
    "groomers": 34,
    "stays": 5
  },
  {
    "official": "경상남도 창원시 진해구",
    "restaurants": 2788,
    "vets": 14,
    "groomers": 45,
    "stays": 8,
    "shelters": 1
  },
  {
    "official": "경상남도 통영시",
    "restaurants": 2259,
    "vets": 15,
    "groomers": 24,
    "stays": 46,
    "shelters": 2,
    "rescueDogs90": 30,
    "tourSpots": 73
  },
  {
    "official": "경상남도 하동군",
    "restaurants": 818,
    "vets": 8,
    "groomers": 3,
    "stays": 2,
    "shelters": 1,
    "rescueDogs90": 37,
    "tourSpots": 58
  },
  {
    "official": "경상남도 함안군",
    "restaurants": 903,
    "vets": 10,
    "groomers": 8,
    "stays": 1,
    "shelters": 1,
    "rescueDogs90": 159,
    "tourSpots": 26
  },
  {
    "official": "경상남도 함양군",
    "restaurants": 650,
    "vets": 8,
    "groomers": 2,
    "stays": 3,
    "shelters": 1,
    "rescueDogs90": 23,
    "tourSpots": 35
  },
  {
    "official": "경상남도 합천군",
    "restaurants": 626,
    "vets": 18,
    "groomers": 2,
    "stays": 1,
    "shelters": 1,
    "rescueDogs90": 75,
    "tourSpots": 29
  },
  {
    "official": "경상북도 경산시",
    "restaurants": 3495,
    "vets": 33,
    "groomers": 72,
    "stays": 1,
    "shelters": 1,
    "rescueDogs90": 101,
    "tourSpots": 17
  },
  {
    "official": "경상북도 경주시",
    "restaurants": 5455,
    "vets": 40,
    "groomers": 37,
    "stays": 45,
    "shelters": 1,
    "rescueDogs90": 182,
    "tourSpots": 100
  },
  {
    "official": "경상북도 고령군",
    "restaurants": 464,
    "vets": 8,
    "groomers": 1,
    "stays": 2,
    "shelters": 1,
    "rescueDogs90": 34,
    "tourSpots": 19
  },
  {
    "official": "경상북도 구미시",
    "restaurants": 5589,
    "vets": 46,
    "groomers": 123,
    "stays": 4,
    "shelters": 1,
    "rescueDogs90": 76,
    "tourSpots": 29
  },
  {
    "official": "경상북도 김천시",
    "restaurants": 2325,
    "vets": 20,
    "groomers": 32,
    "shelters": 1,
    "rescueDogs90": 52,
    "tourSpots": 19
  },
  {
    "official": "경상북도 문경시",
    "restaurants": 1348,
    "vets": 10,
    "groomers": 10,
    "stays": 5,
    "shelters": 1,
    "rescueDogs90": 71,
    "tourSpots": 20
  },
  {
    "official": "경상북도 봉화군",
    "restaurants": 478,
    "vets": 8,
    "groomers": 1,
    "stays": 1,
    "shelters": 1,
    "rescueDogs90": 15,
    "tourSpots": 29
  },
  {
    "official": "경상북도 상주시",
    "restaurants": 1366,
    "vets": 26,
    "groomers": 10,
    "stays": 1,
    "shelters": 1,
    "rescueDogs90": 62,
    "tourSpots": 42
  },
  {
    "official": "경상북도 성주군",
    "restaurants": 676,
    "vets": 10,
    "groomers": 1,
    "stays": 1,
    "shelters": 1,
    "rescueDogs90": 51,
    "tourSpots": 21
  },
  {
    "official": "경상북도 안동시",
    "restaurants": 2647,
    "vets": 16,
    "groomers": 14,
    "stays": 13,
    "shelters": 1,
    "rescueDogs90": 46,
    "tourSpots": 62
  },
  {
    "official": "경상북도 영덕군",
    "restaurants": 943,
    "vets": 3,
    "groomers": 2,
    "stays": 4,
    "shelters": 2,
    "rescueDogs90": 35,
    "tourSpots": 34
  },
  {
    "official": "경상북도 영양군",
    "restaurants": 214,
    "vets": 2,
    "shelters": 1,
    "rescueDogs90": 6,
    "tourSpots": 8
  },
  {
    "official": "경상북도 영주시",
    "restaurants": 1635,
    "vets": 16,
    "groomers": 14,
    "stays": 4,
    "shelters": 1,
    "rescueDogs90": 64,
    "tourSpots": 35
  },
  {
    "official": "경상북도 영천시",
    "restaurants": 1542,
    "vets": 22,
    "groomers": 16,
    "stays": 3,
    "shelters": 1,
    "rescueDogs90": 84,
    "tourSpots": 38
  },
  {
    "official": "경상북도 예천군",
    "restaurants": 755,
    "vets": 13,
    "groomers": 5,
    "shelters": 1,
    "rescueDogs90": 36,
    "tourSpots": 37
  },
  {
    "official": "경상북도 울릉군",
    "restaurants": 292,
    "vets": 1,
    "groomers": 1,
    "stays": 25,
    "shelters": 1,
    "tourSpots": 37
  },
  {
    "official": "경상북도 울진군",
    "restaurants": 1000,
    "vets": 5,
    "groomers": 11,
    "stays": 9,
    "shelters": 1,
    "rescueDogs90": 60,
    "tourSpots": 32
  },
  {
    "official": "경상북도 의성군",
    "restaurants": 660,
    "vets": 14,
    "groomers": 1,
    "shelters": 1,
    "rescueDogs90": 71,
    "tourSpots": 25
  },
  {
    "official": "경상북도 청도군",
    "restaurants": 706,
    "vets": 9,
    "groomers": 3,
    "stays": 1,
    "shelters": 1,
    "rescueDogs90": 64,
    "tourSpots": 34
  },
  {
    "official": "경상북도 청송군",
    "restaurants": 587,
    "vets": 3,
    "stays": 2,
    "shelters": 1,
    "rescueDogs90": 21,
    "tourSpots": 27
  },
  {
    "official": "경상북도 칠곡군",
    "restaurants": 1889,
    "vets": 11,
    "groomers": 25,
    "stays": 1,
    "shelters": 3,
    "rescueDogs90": 38,
    "tourSpots": 20
  },
  {
    "official": "경상북도 포항시",
    "restaurants": 7787,
    "vets": 38,
    "groomers": 116,
    "stays": 21,
    "shelters": 1,
    "rescueDogs90": 171,
    "tourSpots": 76
  },
  {
    "official": "광주광역시 광산구",
    "tourSpots": 16
  },
  {
    "official": "광주광역시 남구",
    "shelters": 1,
    "tourSpots": 13
  },
  {
    "official": "광주광역시 동구",
    "shelters": 1,
    "tourSpots": 13
  },
  {
    "official": "광주광역시 북구",
    "shelters": 2,
    "tourSpots": 27
  },
  {
    "official": "광주광역시 서구",
    "tourSpots": 7
  },
  {
    "official": "대구광역시 군위군",
    "restaurants": 356,
    "vets": 9,
    "stays": 1,
    "shelters": 1,
    "rescueDogs90": 40,
    "tourSpots": 26
  },
  {
    "official": "대구광역시 남구",
    "restaurants": 1928,
    "vets": 12,
    "groomers": 54,
    "stays": 6,
    "rescueDogs90": 16,
    "tourSpots": 11
  },
  {
    "official": "대구광역시 달서구",
    "restaurants": 5733,
    "vets": 46,
    "groomers": 123,
    "stays": 2,
    "shelters": 3,
    "rescueDogs90": 28,
    "tourSpots": 19
  },
  {
    "official": "대구광역시 달서구 상인동",
    "restaurants": 683,
    "vets": 6,
    "groomers": 12
  },
  {
    "official": "대구광역시 달서구 월성동",
    "restaurants": 355,
    "vets": 4,
    "groomers": 9
  },
  {
    "official": "대구광역시 달서구 이곡동",
    "restaurants": 411,
    "vets": 5,
    "groomers": 8,
    "stays": 1
  },
  {
    "official": "대구광역시 달성군",
    "restaurants": 3017,
    "vets": 15,
    "groomers": 48,
    "stays": 1,
    "rescueDogs90": 47,
    "tourSpots": 47
  },
  {
    "official": "대구광역시 달성군 다사읍",
    "restaurants": 718,
    "vets": 5,
    "groomers": 18
  },
  {
    "official": "대구광역시 달성군 현풍읍",
    "restaurants": 469,
    "vets": 4,
    "groomers": 9
  },
  {
    "official": "대구광역시 달성군 화원읍",
    "restaurants": 421,
    "vets": 1,
    "groomers": 9,
    "shelters": 1
  },
  {
    "official": "대구광역시 동구",
    "restaurants": 4063,
    "vets": 22,
    "groomers": 76,
    "stays": 13,
    "shelters": 4,
    "rescueDogs90": 61,
    "tourSpots": 34
  },
  {
    "official": "대구광역시 동구 신서동",
    "restaurants": 244,
    "vets": 3,
    "groomers": 8
  },
  {
    "official": "대구광역시 동구 신암동",
    "restaurants": 544,
    "vets": 5,
    "groomers": 11,
    "stays": 1
  },
  {
    "official": "대구광역시 북구",
    "restaurants": 4607,
    "vets": 35,
    "groomers": 99,
    "stays": 2,
    "shelters": 2,
    "rescueDogs90": 48,
    "tourSpots": 16
  },
  {
    "official": "대구광역시 북구 산격동",
    "restaurants": 691,
    "vets": 3,
    "groomers": 5,
    "stays": 1
  },
  {
    "official": "대구광역시 북구 칠성동",
    "restaurants": 268,
    "vets": 2,
    "groomers": 4
  },
  {
    "official": "대구광역시 북구 침산동",
    "restaurants": 297,
    "vets": 3,
    "groomers": 8
  },
  {
    "official": "대구광역시 서구",
    "restaurants": 2247,
    "vets": 11,
    "groomers": 37,
    "shelters": 5,
    "rescueDogs90": 37,
    "tourSpots": 8
  },
  {
    "official": "대구광역시 수성구",
    "restaurants": 4474,
    "vets": 46,
    "groomers": 122,
    "stays": 5,
    "shelters": 7,
    "rescueDogs90": 31,
    "tourSpots": 14
  },
  {
    "official": "대구광역시 수성구 만촌동",
    "restaurants": 370,
    "vets": 8,
    "groomers": 14,
    "stays": 1
  },
  {
    "official": "대구광역시 수성구 범어동",
    "restaurants": 899,
    "vets": 6,
    "groomers": 11,
    "stays": 2
  },
  {
    "official": "대구광역시 수성구 시지동",
    "restaurants": 137,
    "vets": 2,
    "groomers": 9
  },
  {
    "official": "대구광역시 수성구 지산동",
    "restaurants": 496,
    "vets": 8,
    "groomers": 12
  },
  {
    "official": "대구광역시 수성구 황금동",
    "restaurants": 306,
    "vets": 4,
    "groomers": 11
  },
  {
    "official": "대구광역시 중구",
    "restaurants": 2966,
    "vets": 18,
    "groomers": 29,
    "stays": 11,
    "shelters": 4,
    "rescueDogs90": 14,
    "tourSpots": 17
  },
  {
    "official": "대구광역시 중구 동성로",
    "restaurants": 112,
    "stays": 1
  },
  {
    "official": "대전광역시 대덕구",
    "restaurants": 2206,
    "vets": 12,
    "groomers": 30,
    "shelters": 1,
    "rescueDogs90": 28,
    "tourSpots": 18
  },
  {
    "official": "대전광역시 동구",
    "restaurants": 2657,
    "vets": 14,
    "groomers": 49,
    "stays": 5,
    "rescueDogs90": 45,
    "tourSpots": 20
  },
  {
    "official": "대전광역시 서구",
    "restaurants": 5780,
    "vets": 36,
    "groomers": 122,
    "stays": 3,
    "shelters": 2,
    "rescueDogs90": 69,
    "tourSpots": 10
  },
  {
    "official": "대전광역시 서구 둔산동",
    "restaurants": 1030,
    "vets": 3,
    "groomers": 11
  },
  {
    "official": "대전광역시 서구 월평동",
    "restaurants": 526,
    "vets": 3,
    "groomers": 8,
    "stays": 3
  },
  {
    "official": "대전광역시 유성구",
    "restaurants": 5123,
    "vets": 39,
    "groomers": 91,
    "stays": 10,
    "shelters": 5,
    "rescueDogs90": 52,
    "tourSpots": 20
  },
  {
    "official": "대전광역시 유성구 관평동",
    "restaurants": 441,
    "vets": 2,
    "groomers": 5,
    "stays": 2
  },
  {
    "official": "대전광역시 유성구 노은동",
    "restaurants": 113,
    "vets": 1,
    "groomers": 3
  },
  {
    "official": "대전광역시 유성구 봉명동",
    "restaurants": 844,
    "vets": 7,
    "groomers": 10,
    "stays": 4
  },
  {
    "official": "대전광역시 중구",
    "restaurants": 3229,
    "vets": 18,
    "groomers": 48,
    "stays": 19,
    "rescueDogs90": 40,
    "tourSpots": 14
  },
  {
    "official": "부산광역시 강서구",
    "restaurants": 2034,
    "vets": 14,
    "groomers": 45,
    "stays": 1,
    "shelters": 9,
    "rescueDogs90": 156,
    "tourSpots": 9
  },
  {
    "official": "부산광역시 강서구 명지동",
    "restaurants": 1045,
    "vets": 10,
    "groomers": 37,
    "stays": 1
  },
  {
    "official": "부산광역시 금정구",
    "restaurants": 2835,
    "vets": 18,
    "groomers": 36,
    "stays": 2,
    "rescueDogs90": 22,
    "tourSpots": 11
  },
  {
    "official": "부산광역시 금정구 구서동",
    "restaurants": 471,
    "vets": 4,
    "groomers": 7,
    "stays": 2
  },
  {
    "official": "부산광역시 금정구 장전동",
    "restaurants": 944,
    "vets": 3,
    "groomers": 13
  },
  {
    "official": "부산광역시 기장군",
    "restaurants": 2591,
    "vets": 14,
    "groomers": 66,
    "stays": 31,
    "rescueDogs90": 43,
    "tourSpots": 14
  },
  {
    "official": "부산광역시 기장군 기장읍",
    "restaurants": 1037,
    "vets": 5,
    "groomers": 19,
    "stays": 15
  },
  {
    "official": "부산광역시 기장군 일광읍",
    "restaurants": 515,
    "vets": 5,
    "groomers": 13,
    "stays": 11
  },
  {
    "official": "부산광역시 기장군 정관읍",
    "restaurants": 735,
    "vets": 2,
    "groomers": 33,
    "stays": 1
  },
  {
    "official": "부산광역시 남구",
    "restaurants": 2683,
    "vets": 19,
    "groomers": 61,
    "stays": 2,
    "rescueDogs90": 16,
    "tourSpots": 8
  },
  {
    "official": "부산광역시 남구 대연동",
    "restaurants": 1441,
    "vets": 7,
    "groomers": 29,
    "stays": 1
  },
  {
    "official": "부산광역시 동구",
    "restaurants": 1348,
    "vets": 5,
    "groomers": 12,
    "stays": 32,
    "shelters": 1,
    "rescueDogs90": 9,
    "tourSpots": 10
  },
  {
    "official": "부산광역시 동래구",
    "restaurants": 3090,
    "vets": 32,
    "groomers": 65,
    "stays": 2,
    "rescueDogs90": 27,
    "tourSpots": 5
  },
  {
    "official": "부산광역시 동래구 사직동",
    "restaurants": 597,
    "vets": 4,
    "groomers": 12,
    "stays": 1
  },
  {
    "official": "부산광역시 동래구 온천동",
    "restaurants": 835,
    "vets": 11,
    "groomers": 21,
    "stays": 1
  },
  {
    "official": "부산광역시 부산진구",
    "restaurants": 5566,
    "vets": 30,
    "groomers": 102,
    "stays": 63,
    "rescueDogs90": 29,
    "tourSpots": 5
  },
  {
    "official": "부산광역시 부산진구 가야동",
    "restaurants": 386,
    "vets": 3,
    "groomers": 8
  },
  {
    "official": "부산광역시 부산진구 부전동",
    "restaurants": 1784,
    "vets": 3,
    "groomers": 8,
    "stays": 36
  },
  {
    "official": "부산광역시 부산진구 양정동",
    "restaurants": 488,
    "vets": 4,
    "groomers": 20
  },
  {
    "official": "부산광역시 부산진구 전포동",
    "restaurants": 1072,
    "vets": 5,
    "groomers": 20,
    "stays": 24
  },
  {
    "official": "부산광역시 북구",
    "restaurants": 2380,
    "vets": 19,
    "groomers": 56,
    "stays": 6,
    "rescueDogs90": 29,
    "tourSpots": 5
  },
  {
    "official": "부산광역시 북구 덕천동",
    "restaurants": 625,
    "vets": 5,
    "groomers": 11,
    "stays": 2
  },
  {
    "official": "부산광역시 북구 만덕동",
    "restaurants": 373,
    "vets": 3,
    "groomers": 12,
    "stays": 2
  },
  {
    "official": "부산광역시 북구 화명동",
    "restaurants": 628,
    "vets": 8,
    "groomers": 17
  },
  {
    "official": "부산광역시 사상구",
    "restaurants": 2437,
    "vets": 12,
    "groomers": 29,
    "stays": 3,
    "rescueDogs90": 19,
    "tourSpots": 4
  },
  {
    "official": "부산광역시 사하구",
    "restaurants": 3063,
    "vets": 20,
    "groomers": 76,
    "stays": 2,
    "rescueDogs90": 19,
    "tourSpots": 7
  },
  {
    "official": "부산광역시 사하구 괴정동",
    "restaurants": 486,
    "vets": 3,
    "groomers": 14
  },
  {
    "official": "부산광역시 사하구 다대동",
    "restaurants": 571,
    "vets": 5,
    "groomers": 20
  },
  {
    "official": "부산광역시 사하구 신평동",
    "restaurants": 319,
    "vets": 3,
    "groomers": 6
  },
  {
    "official": "부산광역시 사하구 하단동",
    "restaurants": 764,
    "vets": 5,
    "groomers": 13,
    "stays": 2
  },
  {
    "official": "부산광역시 서구",
    "restaurants": 1125,
    "vets": 7,
    "groomers": 22,
    "stays": 5,
    "rescueDogs90": 18,
    "tourSpots": 7
  },
  {
    "official": "부산광역시 수영구",
    "restaurants": 2855,
    "vets": 22,
    "groomers": 72,
    "stays": 165,
    "rescueDogs90": 14,
    "tourSpots": 9
  },
  {
    "official": "부산광역시 수영구 광안동",
    "restaurants": 1034,
    "vets": 7,
    "groomers": 25,
    "stays": 40
  },
  {
    "official": "부산광역시 수영구 남천동",
    "restaurants": 508,
    "vets": 3,
    "groomers": 12,
    "stays": 6
  },
  {
    "official": "부산광역시 수영구 민락동",
    "restaurants": 755,
    "vets": 5,
    "groomers": 10,
    "stays": 117
  },
  {
    "official": "부산광역시 연제구",
    "restaurants": 2405,
    "vets": 17,
    "groomers": 57,
    "stays": 5,
    "shelters": 1,
    "rescueDogs90": 16,
    "tourSpots": 3
  },
  {
    "official": "부산광역시 연제구 연산동",
    "restaurants": 1891,
    "vets": 14,
    "groomers": 45,
    "stays": 5
  },
  {
    "official": "부산광역시 영도구",
    "restaurants": 1221,
    "vets": 4,
    "groomers": 20,
    "stays": 4,
    "rescueDogs90": 8,
    "tourSpots": 13
  },
  {
    "official": "부산광역시 중구",
    "restaurants": 2159,
    "vets": 2,
    "groomers": 16,
    "stays": 31,
    "rescueDogs90": 6,
    "tourSpots": 11
  },
  {
    "official": "부산광역시 중구 남포동",
    "restaurants": 493,
    "vets": 2,
    "stays": 9
  },
  {
    "official": "부산광역시 해운대구",
    "restaurants": 4321,
    "vets": 44,
    "groomers": 121,
    "stays": 101,
    "shelters": 5,
    "rescueDogs90": 28,
    "tourSpots": 19
  },
  {
    "official": "부산광역시 해운대구 송정동",
    "restaurants": 248,
    "vets": 2,
    "groomers": 2,
    "stays": 54
  },
  {
    "official": "부산광역시 해운대구 우동",
    "restaurants": 1007,
    "vets": 12,
    "groomers": 30,
    "stays": 18
  },
  {
    "official": "부산광역시 해운대구 재송동",
    "restaurants": 544,
    "vets": 5,
    "groomers": 12,
    "stays": 2
  },
  {
    "official": "부산광역시 해운대구 좌동",
    "restaurants": 744,
    "vets": 14,
    "groomers": 31,
    "stays": 1
  },
  {
    "official": "서울특별시 강남구",
    "restaurants": 12201,
    "vets": 94,
    "groomers": 162,
    "stays": 82,
    "rescueDogs90": 9,
    "tourSpots": 20
  },
  {
    "official": "서울특별시 강남구 개포동",
    "restaurants": 386,
    "vets": 11,
    "groomers": 12,
    "stays": 1
  },
  {
    "official": "서울특별시 강남구 논현동",
    "restaurants": 2037,
    "vets": 14,
    "groomers": 43,
    "stays": 18
  },
  {
    "official": "서울특별시 강남구 대치동",
    "restaurants": 1390,
    "vets": 7,
    "groomers": 10,
    "stays": 6
  },
  {
    "official": "서울특별시 강남구 도곡동",
    "restaurants": 506,
    "vets": 5,
    "groomers": 6
  },
  {
    "official": "서울특별시 강남구 삼성동",
    "restaurants": 1240,
    "vets": 8,
    "groomers": 17,
    "stays": 13
  },
  {
    "official": "서울특별시 강남구 세곡동",
    "restaurants": 78,
    "vets": 1,
    "groomers": 1
  },
  {
    "official": "서울특별시 강남구 수서동",
    "restaurants": 185,
    "vets": 1,
    "groomers": 1
  },
  {
    "official": "서울특별시 강남구 신사동",
    "restaurants": 1943,
    "vets": 10,
    "groomers": 16,
    "stays": 9
  },
  {
    "official": "서울특별시 강남구 압구정동",
    "restaurants": 104,
    "vets": 2,
    "groomers": 3
  },
  {
    "official": "서울특별시 강남구 역삼동",
    "restaurants": 3083,
    "vets": 15,
    "groomers": 31,
    "stays": 30
  },
  {
    "official": "서울특별시 강남구 일원동",
    "restaurants": 200,
    "vets": 4,
    "groomers": 5
  },
  {
    "official": "서울특별시 강남구 청담동",
    "restaurants": 935,
    "vets": 14,
    "groomers": 14,
    "stays": 5
  },
  {
    "official": "서울특별시 강동구",
    "restaurants": 3924,
    "vets": 50,
    "groomers": 102,
    "stays": 6,
    "shelters": 4,
    "rescueDogs90": 23,
    "tourSpots": 8
  },
  {
    "official": "서울특별시 강동구 강일동",
    "restaurants": 67,
    "vets": 2,
    "groomers": 4
  },
  {
    "official": "서울특별시 강동구 고덕동",
    "restaurants": 253,
    "vets": 5,
    "groomers": 10
  },
  {
    "official": "서울특별시 강동구 길동",
    "restaurants": 557,
    "vets": 7,
    "groomers": 14,
    "stays": 1
  },
  {
    "official": "서울특별시 강동구 둔촌동",
    "restaurants": 207,
    "vets": 5,
    "groomers": 7
  },
  {
    "official": "서울특별시 강동구 명일동",
    "restaurants": 346,
    "vets": 3,
    "groomers": 9
  },
  {
    "official": "서울특별시 강동구 상일동",
    "restaurants": 180,
    "vets": 4,
    "groomers": 4
  },
  {
    "official": "서울특별시 강동구 암사동",
    "restaurants": 365,
    "vets": 6,
    "groomers": 16
  },
  {
    "official": "서울특별시 강동구 천호동",
    "restaurants": 1012,
    "vets": 9,
    "groomers": 16,
    "stays": 3
  },
  {
    "official": "서울특별시 강북구",
    "restaurants": 3217,
    "vets": 28,
    "groomers": 56,
    "stays": 7,
    "rescueDogs90": 44,
    "tourSpots": 12
  },
  {
    "official": "서울특별시 강북구 미아동",
    "restaurants": 1269,
    "vets": 17,
    "groomers": 26,
    "stays": 1
  },
  {
    "official": "서울특별시 강북구 번동",
    "restaurants": 387,
    "vets": 3,
    "groomers": 5
  },
  {
    "official": "서울특별시 강북구 수유동",
    "restaurants": 1387,
    "vets": 8,
    "groomers": 22,
    "stays": 5
  },
  {
    "official": "서울특별시 강북구 우이동",
    "restaurants": 174,
    "groomers": 3,
    "stays": 1
  },
  {
    "official": "서울특별시 강서구",
    "restaurants": 5495,
    "vets": 50,
    "groomers": 112,
    "stays": 21,
    "rescueDogs90": 38,
    "tourSpots": 5
  },
  {
    "official": "서울특별시 강서구 가양동",
    "restaurants": 146,
    "vets": 3,
    "groomers": 5
  },
  {
    "official": "서울특별시 강서구 내발산동",
    "restaurants": 279,
    "vets": 5,
    "groomers": 11
  },
  {
    "official": "서울특별시 강서구 등촌동",
    "restaurants": 630,
    "vets": 6,
    "groomers": 16,
    "stays": 2
  },
  {
    "official": "서울특별시 강서구 마곡동",
    "restaurants": 1530,
    "vets": 8,
    "groomers": 18,
    "stays": 3
  },
  {
    "official": "서울특별시 강서구 방화동",
    "restaurants": 483,
    "vets": 6,
    "groomers": 12,
    "stays": 1
  },
  {
    "official": "서울특별시 강서구 염창동",
    "restaurants": 180,
    "vets": 3,
    "groomers": 8,
    "stays": 3
  },
  {
    "official": "서울특별시 강서구 화곡동",
    "restaurants": 1964,
    "vets": 18,
    "groomers": 39,
    "stays": 6
  },
  {
    "official": "서울특별시 관악구",
    "restaurants": 4649,
    "vets": 28,
    "groomers": 55,
    "stays": 16,
    "rescueDogs90": 53,
    "tourSpots": 7
  },
  {
    "official": "서울특별시 관악구 봉천동",
    "restaurants": 2189,
    "vets": 16,
    "groomers": 23,
    "stays": 2
  },
  {
    "official": "서울특별시 관악구 신림동",
    "restaurants": 2264,
    "vets": 12,
    "groomers": 31,
    "stays": 13
  },
  {
    "official": "서울특별시 광진구",
    "restaurants": 4272,
    "vets": 33,
    "groomers": 60,
    "stays": 20,
    "rescueDogs90": 10,
    "tourSpots": 14
  },
  {
    "official": "서울특별시 광진구 광장동",
    "restaurants": 167,
    "vets": 3,
    "groomers": 6,
    "stays": 3
  },
  {
    "official": "서울특별시 광진구 구의동",
    "restaurants": 837,
    "vets": 6,
    "groomers": 12,
    "stays": 1
  },
  {
    "official": "서울특별시 광진구 능동",
    "restaurants": 146,
    "vets": 2,
    "groomers": 1,
    "stays": 1
  },
  {
    "official": "서울특별시 광진구 자양동",
    "restaurants": 1018,
    "vets": 10,
    "groomers": 17,
    "stays": 3
  },
  {
    "official": "서울특별시 광진구 중곡동",
    "restaurants": 885,
    "vets": 7,
    "groomers": 19,
    "stays": 1
  },
  {
    "official": "서울특별시 광진구 화양동",
    "restaurants": 853,
    "vets": 2,
    "groomers": 2,
    "stays": 8
  },
  {
    "official": "서울특별시 구로구",
    "restaurants": 4017,
    "vets": 29,
    "groomers": 48,
    "stays": 15,
    "shelters": 1,
    "rescueDogs90": 18,
    "tourSpots": 22
  },
  {
    "official": "서울특별시 구로구 가리봉동",
    "restaurants": 184,
    "stays": 7
  },
  {
    "official": "서울특별시 구로구 개봉동",
    "restaurants": 479,
    "vets": 6,
    "groomers": 11
  },
  {
    "official": "서울특별시 구로구 고척동",
    "restaurants": 464,
    "vets": 5,
    "groomers": 9
  },
  {
    "official": "서울특별시 구로구 신도림동",
    "restaurants": 240,
    "vets": 5,
    "groomers": 4,
    "stays": 2
  },
  {
    "official": "서울특별시 구로구 오류동",
    "restaurants": 297,
    "vets": 3,
    "groomers": 5,
    "stays": 1
  },
  {
    "official": "서울특별시 구로구 온수동",
    "restaurants": 51,
    "groomers": 1
  },
  {
    "official": "서울특별시 구로구 천왕동",
    "restaurants": 25,
    "vets": 1,
    "groomers": 1
  },
  {
    "official": "서울특별시 구로구 항동",
    "restaurants": 55,
    "vets": 2,
    "groomers": 4
  },
  {
    "official": "서울특별시 금천구",
    "restaurants": 3069,
    "vets": 16,
    "groomers": 42,
    "stays": 12,
    "rescueDogs90": 12,
    "tourSpots": 5
  },
  {
    "official": "서울특별시 금천구 가산동",
    "restaurants": 1143,
    "groomers": 5,
    "stays": 4
  },
  {
    "official": "서울특별시 금천구 독산동",
    "restaurants": 1099,
    "vets": 9,
    "groomers": 20,
    "stays": 7
  },
  {
    "official": "서울특별시 노원구",
    "restaurants": 3559,
    "vets": 45,
    "groomers": 86,
    "stays": 2,
    "shelters": 1,
    "rescueDogs90": 24,
    "tourSpots": 10
  },
  {
    "official": "서울특별시 노원구 공릉동",
    "restaurants": 881,
    "vets": 8,
    "groomers": 15
  },
  {
    "official": "서울특별시 노원구 상계동",
    "restaurants": 1610,
    "vets": 22,
    "groomers": 45,
    "stays": 2
  },
  {
    "official": "서울특별시 노원구 월계동",
    "restaurants": 389,
    "vets": 4,
    "groomers": 6
  },
  {
    "official": "서울특별시 노원구 중계동",
    "restaurants": 503,
    "vets": 11,
    "groomers": 17
  },
  {
    "official": "서울특별시 노원구 하계동",
    "restaurants": 176,
    "groomers": 3
  },
  {
    "official": "서울특별시 도봉구",
    "restaurants": 2180,
    "vets": 25,
    "groomers": 61,
    "stays": 3,
    "rescueDogs90": 13,
    "tourSpots": 7
  },
  {
    "official": "서울특별시 도봉구 도봉동",
    "restaurants": 429,
    "vets": 4,
    "groomers": 10,
    "stays": 1
  },
  {
    "official": "서울특별시 도봉구 방학동",
    "restaurants": 560,
    "vets": 7,
    "groomers": 15,
    "stays": 1
  },
  {
    "official": "서울특별시 도봉구 쌍문동",
    "restaurants": 445,
    "vets": 8,
    "groomers": 14,
    "stays": 1
  },
  {
    "official": "서울특별시 도봉구 창동",
    "restaurants": 746,
    "vets": 6,
    "groomers": 22
  },
  {
    "official": "서울특별시 동대문구",
    "restaurants": 3895,
    "vets": 32,
    "groomers": 57,
    "stays": 18,
    "shelters": 1,
    "rescueDogs90": 26,
    "tourSpots": 6
  },
  {
    "official": "서울특별시 동대문구 답십리동",
    "restaurants": 313,
    "vets": 6,
    "groomers": 12,
    "stays": 2
  },
  {
    "official": "서울특별시 동대문구 신설동",
    "restaurants": 207,
    "vets": 1,
    "stays": 3
  },
  {
    "official": "서울특별시 동대문구 용두동",
    "restaurants": 331,
    "vets": 4,
    "groomers": 5,
    "stays": 3
  },
  {
    "official": "서울특별시 동대문구 이문동",
    "restaurants": 348,
    "vets": 4,
    "groomers": 6,
    "stays": 1
  },
  {
    "official": "서울특별시 동대문구 장안동",
    "restaurants": 915,
    "vets": 8,
    "groomers": 16,
    "stays": 3
  },
  {
    "official": "서울특별시 동대문구 전농동",
    "restaurants": 463,
    "vets": 5,
    "groomers": 8,
    "stays": 2
  },
  {
    "official": "서울특별시 동대문구 제기동",
    "restaurants": 462,
    "groomers": 2,
    "stays": 1
  },
  {
    "official": "서울특별시 동대문구 회기동",
    "restaurants": 378,
    "vets": 1,
    "groomers": 2
  },
  {
    "official": "서울특별시 동대문구 휘경동",
    "restaurants": 248,
    "vets": 2,
    "groomers": 4,
    "stays": 1
  },
  {
    "official": "서울특별시 동작구",
    "restaurants": 3153,
    "vets": 22,
    "groomers": 48,
    "stays": 8,
    "shelters": 2,
    "rescueDogs90": 16,
    "tourSpots": 5
  },
  {
    "official": "서울특별시 동작구 노량진동",
    "restaurants": 480,
    "vets": 2,
    "groomers": 2,
    "stays": 4
  },
  {
    "official": "서울특별시 동작구 대방동",
    "restaurants": 204,
    "vets": 2,
    "groomers": 6
  },
  {
    "official": "서울특별시 동작구 동작동",
    "restaurants": 6,
    "groomers": 1
  },
  {
    "official": "서울특별시 동작구 사당동",
    "restaurants": 1006,
    "vets": 10,
    "groomers": 13,
    "stays": 2
  },
  {
    "official": "서울특별시 동작구 상도동",
    "restaurants": 646,
    "vets": 5,
    "groomers": 13,
    "stays": 1
  },
  {
    "official": "서울특별시 동작구 신대방동",
    "restaurants": 364,
    "groomers": 6,
    "stays": 1
  },
  {
    "official": "서울특별시 동작구 흑석동",
    "restaurants": 304,
    "vets": 2,
    "groomers": 4
  },
  {
    "official": "서울특별시 마포구",
    "restaurants": 7805,
    "vets": 51,
    "groomers": 66,
    "stays": 46,
    "shelters": 7,
    "rescueDogs90": 19,
    "tourSpots": 24
  },
  {
    "official": "서울특별시 마포구 공덕동",
    "restaurants": 408,
    "vets": 4,
    "groomers": 4,
    "stays": 1
  },
  {
    "official": "서울특별시 마포구 대흥동",
    "restaurants": 217,
    "vets": 4,
    "groomers": 3
  },
  {
    "official": "서울특별시 마포구 망원동",
    "restaurants": 726,
    "vets": 4,
    "groomers": 8
  },
  {
    "official": "서울특별시 마포구 상수동",
    "restaurants": 281,
    "vets": 1,
    "groomers": 1,
    "stays": 1
  },
  {
    "official": "서울특별시 마포구 상암동",
    "restaurants": 618,
    "vets": 5,
    "groomers": 4,
    "stays": 1
  },
  {
    "official": "서울특별시 마포구 서교동",
    "restaurants": 1749,
    "vets": 6,
    "groomers": 7,
    "stays": 13
  },
  {
    "official": "서울특별시 마포구 성산동",
    "restaurants": 366,
    "vets": 6,
    "groomers": 6
  },
  {
    "official": "서울특별시 마포구 연남동",
    "restaurants": 780,
    "groomers": 6,
    "stays": 1
  },
  {
    "official": "서울특별시 마포구 합정동",
    "restaurants": 569,
    "vets": 1,
    "groomers": 3,
    "stays": 2
  },
  {
    "official": "서울특별시 서대문구",
    "restaurants": 3553,
    "vets": 28,
    "groomers": 57,
    "stays": 21,
    "shelters": 1,
    "rescueDogs90": 12,
    "tourSpots": 14
  },
  {
    "official": "서울특별시 서대문구 남가좌동",
    "restaurants": 402,
    "vets": 6,
    "groomers": 12
  },
  {
    "official": "서울특별시 서대문구 대현동",
    "restaurants": 265,
    "groomers": 1,
    "stays": 8
  },
  {
    "official": "서울특별시 서대문구 북아현동",
    "restaurants": 125,
    "vets": 3,
    "groomers": 3
  },
  {
    "official": "서울특별시 서대문구 신촌동",
    "restaurants": 24
  },
  {
    "official": "서울특별시 서대문구 연희동",
    "restaurants": 386,
    "vets": 5,
    "groomers": 9,
    "stays": 1
  },
  {
    "official": "서울특별시 서대문구 충정로",
    "restaurants": 233,
    "groomers": 1
  },
  {
    "official": "서울특별시 서대문구 현저동",
    "restaurants": 3,
    "groomers": 1
  },
  {
    "official": "서울특별시 서대문구 홍제동",
    "restaurants": 444,
    "vets": 4,
    "groomers": 10,
    "stays": 1
  },
  {
    "official": "서울특별시 서초구",
    "restaurants": 5562,
    "vets": 62,
    "groomers": 93,
    "stays": 13,
    "shelters": 1,
    "rescueDogs90": 18,
    "tourSpots": 19
  },
  {
    "official": "서울특별시 서초구 내곡동",
    "restaurants": 26,
    "groomers": 1
  },
  {
    "official": "서울특별시 서초구 반포동",
    "restaurants": 774,
    "vets": 13,
    "groomers": 20,
    "stays": 2
  },
  {
    "official": "서울특별시 서초구 방배동",
    "restaurants": 1128,
    "vets": 17,
    "groomers": 28
  },
  {
    "official": "서울특별시 서초구 서초동",
    "restaurants": 2075,
    "vets": 15,
    "groomers": 20,
    "stays": 7
  },
  {
    "official": "서울특별시 서초구 양재동",
    "restaurants": 933,
    "vets": 5,
    "groomers": 14
  },
  {
    "official": "서울특별시 서초구 우면동",
    "restaurants": 77,
    "vets": 3,
    "groomers": 2
  },
  {
    "official": "서울특별시 서초구 잠원동",
    "restaurants": 464,
    "vets": 8,
    "groomers": 7,
    "stays": 3
  },
  {
    "official": "서울특별시 성동구",
    "restaurants": 3933,
    "vets": 26,
    "groomers": 57,
    "stays": 17,
    "shelters": 6,
    "rescueDogs90": 9,
    "tourSpots": 13
  },
  {
    "official": "서울특별시 성동구 금호동",
    "restaurants": 357,
    "vets": 5,
    "groomers": 9
  },
  {
    "official": "서울특별시 성동구 마장동",
    "restaurants": 177,
    "vets": 2,
    "groomers": 2
  },
  {
    "official": "서울특별시 성동구 사근동",
    "restaurants": 45
  },
  {
    "official": "서울특별시 성동구 성수동",
    "restaurants": 1891,
    "vets": 5,
    "groomers": 13,
    "stays": 7
  },
  {
    "official": "서울특별시 성동구 옥수동",
    "restaurants": 124,
    "vets": 3,
    "groomers": 4,
    "stays": 1
  },
  {
    "official": "서울특별시 성동구 행당동",
    "restaurants": 563,
    "vets": 7,
    "groomers": 9,
    "stays": 1
  },
  {
    "official": "서울특별시 성북구",
    "restaurants": 3733,
    "vets": 34,
    "groomers": 77,
    "stays": 4,
    "rescueDogs90": 19,
    "tourSpots": 13
  },
  {
    "official": "서울특별시 성북구 길음동",
    "restaurants": 222,
    "vets": 6,
    "groomers": 10
  },
  {
    "official": "서울특별시 성북구 동선동",
    "restaurants": 497,
    "vets": 1,
    "groomers": 3,
    "stays": 4
  },
  {
    "official": "서울특별시 성북구 보문동",
    "restaurants": 152,
    "vets": 3,
    "groomers": 7
  },
  {
    "official": "서울특별시 성북구 삼선동",
    "restaurants": 214,
    "groomers": 6
  },
  {
    "official": "서울특별시 성북구 안암동",
    "restaurants": 387,
    "groomers": 2
  },
  {
    "official": "서울특별시 성북구 장위동",
    "restaurants": 333,
    "vets": 5,
    "groomers": 13
  },
  {
    "official": "서울특별시 성북구 정릉동",
    "restaurants": 429,
    "vets": 2,
    "groomers": 7
  },
  {
    "official": "서울특별시 성북구 종암동",
    "restaurants": 256,
    "vets": 3,
    "groomers": 5
  },
  {
    "official": "서울특별시 송파구",
    "restaurants": 7023,
    "vets": 89,
    "groomers": 147,
    "stays": 26,
    "rescueDogs90": 12,
    "tourSpots": 14
  },
  {
    "official": "서울특별시 송파구 가락동",
    "restaurants": 897,
    "vets": 10,
    "groomers": 14,
    "stays": 3
  },
  {
    "official": "서울특별시 송파구 거여동",
    "restaurants": 258,
    "vets": 8,
    "groomers": 11
  },
  {
    "official": "서울특별시 송파구 마천동",
    "restaurants": 288,
    "vets": 1,
    "groomers": 4
  },
  {
    "official": "서울특별시 송파구 문정동",
    "restaurants": 1143,
    "vets": 10,
    "groomers": 24,
    "stays": 2
  },
  {
    "official": "서울특별시 송파구 방이동",
    "restaurants": 969,
    "vets": 11,
    "groomers": 13,
    "stays": 7
  },
  {
    "official": "서울특별시 송파구 석촌동",
    "restaurants": 577,
    "vets": 8,
    "groomers": 13,
    "stays": 3
  },
  {
    "official": "서울특별시 송파구 오금동",
    "restaurants": 273,
    "vets": 8,
    "groomers": 13
  },
  {
    "official": "서울특별시 송파구 잠실동",
    "restaurants": 952,
    "vets": 10,
    "groomers": 18,
    "stays": 6
  },
  {
    "official": "서울특별시 송파구 장지동",
    "restaurants": 146,
    "vets": 3,
    "groomers": 7
  },
  {
    "official": "서울특별시 송파구 풍납동",
    "restaurants": 183,
    "vets": 1,
    "groomers": 4
  },
  {
    "official": "서울특별시 양천구",
    "restaurants": 3009,
    "vets": 49,
    "groomers": 75,
    "stays": 1,
    "rescueDogs90": 10,
    "tourSpots": 15
  },
  {
    "official": "서울특별시 양천구 목동",
    "restaurants": 1125,
    "vets": 21,
    "groomers": 23
  },
  {
    "official": "서울특별시 양천구 신월동",
    "restaurants": 851,
    "vets": 12,
    "groomers": 28,
    "stays": 1
  },
  {
    "official": "서울특별시 양천구 신정동",
    "restaurants": 1033,
    "vets": 16,
    "groomers": 24
  },
  {
    "official": "서울특별시 영등포구",
    "restaurants": 6778,
    "vets": 40,
    "groomers": 62,
    "stays": 45,
    "rescueDogs90": 12,
    "tourSpots": 17
  },
  {
    "official": "서울특별시 영등포구 당산동",
    "restaurants": 940,
    "vets": 4,
    "groomers": 7,
    "stays": 10
  },
  {
    "official": "서울특별시 영등포구 대림동",
    "restaurants": 841,
    "vets": 2,
    "groomers": 2
  },
  {
    "official": "서울특별시 영등포구 문래동",
    "restaurants": 658,
    "vets": 3,
    "groomers": 4
  },
  {
    "official": "서울특별시 영등포구 신길동",
    "restaurants": 767,
    "vets": 16,
    "groomers": 25,
    "stays": 2
  },
  {
    "official": "서울특별시 영등포구 양평동",
    "restaurants": 587,
    "vets": 3,
    "groomers": 5,
    "stays": 14
  },
  {
    "official": "서울특별시 영등포구 여의도동",
    "restaurants": 1793,
    "vets": 6,
    "groomers": 6,
    "stays": 6
  },
  {
    "official": "서울특별시 용산구",
    "restaurants": 5107,
    "vets": 28,
    "groomers": 36,
    "stays": 22,
    "shelters": 2,
    "rescueDogs90": 14,
    "tourSpots": 19
  },
  {
    "official": "서울특별시 용산구 갈월동",
    "restaurants": 108,
    "stays": 2
  },
  {
    "official": "서울특별시 용산구 남영동",
    "restaurants": 165
  },
  {
    "official": "서울특별시 용산구 동자동",
    "restaurants": 179,
    "stays": 2
  },
  {
    "official": "서울특별시 용산구 서빙고동",
    "restaurants": 14
  },
  {
    "official": "서울특별시 용산구 이촌동",
    "restaurants": 182,
    "vets": 4,
    "groomers": 4,
    "stays": 1,
    "shelters": 1
  },
  {
    "official": "서울특별시 용산구 이태원동",
    "restaurants": 1038,
    "vets": 2,
    "groomers": 8,
    "stays": 8
  },
  {
    "official": "서울특별시 용산구 한강로1가",
    "restaurants": 195
  },
  {
    "official": "서울특별시 용산구 한강로2가",
    "restaurants": 419,
    "vets": 2
  },
  {
    "official": "서울특별시 용산구 한남동",
    "restaurants": 715,
    "vets": 4,
    "groomers": 6,
    "stays": 2,
    "shelters": 1
  },
  {
    "official": "서울특별시 용산구 효창동",
    "restaurants": 52,
    "vets": 2,
    "groomers": 2
  },
  {
    "official": "서울특별시 용산구 후암동",
    "restaurants": 212,
    "vets": 2,
    "groomers": 2
  },
  {
    "official": "서울특별시 은평구",
    "restaurants": 3654,
    "vets": 44,
    "groomers": 87,
    "stays": 11,
    "rescueDogs90": 39,
    "tourSpots": 8
  },
  {
    "official": "서울특별시 은평구 갈현동",
    "restaurants": 620,
    "vets": 5,
    "groomers": 10,
    "stays": 1
  },
  {
    "official": "서울특별시 은평구 구산동",
    "restaurants": 108,
    "vets": 1,
    "groomers": 5
  },
  {
    "official": "서울특별시 은평구 녹번동",
    "restaurants": 232,
    "vets": 2,
    "groomers": 4,
    "stays": 2
  },
  {
    "official": "서울특별시 은평구 불광동",
    "restaurants": 420,
    "vets": 4,
    "groomers": 8,
    "stays": 2
  },
  {
    "official": "서울특별시 은평구 수색동",
    "restaurants": 80,
    "vets": 2,
    "groomers": 4,
    "stays": 1
  },
  {
    "official": "서울특별시 은평구 역촌동",
    "restaurants": 410,
    "vets": 2,
    "groomers": 9
  },
  {
    "official": "서울특별시 은평구 응암동",
    "restaurants": 722,
    "vets": 9,
    "groomers": 15,
    "stays": 2
  },
  {
    "official": "서울특별시 은평구 증산동",
    "restaurants": 115,
    "vets": 3,
    "groomers": 3
  },
  {
    "official": "서울특별시 은평구 진관동",
    "restaurants": 288,
    "vets": 7,
    "groomers": 11
  },
  {
    "official": "서울특별시 종로구",
    "restaurants": 6640,
    "vets": 12,
    "groomers": 16,
    "stays": 159,
    "rescueDogs90": 12,
    "tourSpots": 66
  },
  {
    "official": "서울특별시 종로구 세종로",
    "restaurants": 41
  },
  {
    "official": "서울특별시 종로구 안국동",
    "restaurants": 40
  },
  {
    "official": "서울특별시 종로구 인사동",
    "restaurants": 159,
    "stays": 1
  },
  {
    "official": "서울특별시 종로구 종로1가",
    "restaurants": 106
  },
  {
    "official": "서울특별시 종로구 혜화동",
    "restaurants": 93,
    "vets": 1
  },
  {
    "official": "서울특별시 중구",
    "restaurants": 6238,
    "vets": 19,
    "groomers": 18,
    "stays": 208,
    "rescueDogs90": 3,
    "tourSpots": 42
  },
  {
    "official": "서울특별시 중구 명동",
    "restaurants": 240,
    "stays": 14
  },
  {
    "official": "서울특별시 중구 신당동",
    "restaurants": 1013,
    "vets": 9,
    "groomers": 13,
    "stays": 1
  },
  {
    "official": "서울특별시 중구 태평로",
    "restaurants": 170,
    "stays": 5
  },
  {
    "official": "서울특별시 중구 필동",
    "restaurants": 273,
    "vets": 1,
    "stays": 3
  },
  {
    "official": "서울특별시 중구 회현동",
    "restaurants": 157,
    "stays": 9
  },
  {
    "official": "서울특별시 중랑구",
    "restaurants": 3453,
    "vets": 31,
    "groomers": 73,
    "stays": 3,
    "rescueDogs90": 18,
    "tourSpots": 6
  },
  {
    "official": "서울특별시 중랑구 망우동",
    "restaurants": 517,
    "vets": 3,
    "groomers": 16
  },
  {
    "official": "서울특별시 중랑구 면목동",
    "restaurants": 1234,
    "vets": 15,
    "groomers": 28
  },
  {
    "official": "서울특별시 중랑구 묵동",
    "restaurants": 393,
    "vets": 3,
    "groomers": 13,
    "stays": 1
  },
  {
    "official": "서울특별시 중랑구 상봉동",
    "restaurants": 643,
    "vets": 4,
    "groomers": 7,
    "stays": 2
  },
  {
    "official": "서울특별시 중랑구 신내동",
    "restaurants": 300,
    "vets": 4,
    "groomers": 5
  },
  {
    "official": "서울특별시 중랑구 중화동",
    "restaurants": 366,
    "vets": 2,
    "groomers": 4
  },
  {
    "official": "세종특별자치시",
    "restaurants": 3827,
    "vets": 35,
    "groomers": 60,
    "stays": 5,
    "shelters": 1,
    "rescueDogs90": 57,
    "tourSpots": 22
  },
  {
    "official": "세종특별자치시 나성동",
    "restaurants": 506,
    "vets": 3,
    "groomers": 5,
    "stays": 2
  },
  {
    "official": "세종특별자치시 도담동",
    "restaurants": 201,
    "vets": 2,
    "groomers": 6
  },
  {
    "official": "세종특별자치시 보람동",
    "restaurants": 251,
    "vets": 1,
    "groomers": 6
  },
  {
    "official": "세종특별자치시 새롬동",
    "restaurants": 96,
    "vets": 1,
    "groomers": 3
  },
  {
    "official": "세종특별자치시 어진동",
    "restaurants": 241,
    "groomers": 2,
    "stays": 2
  },
  {
    "official": "울산광역시 남구",
    "restaurants": 4968,
    "vets": 28,
    "groomers": 107,
    "stays": 14,
    "shelters": 5,
    "rescueDogs90": 25,
    "tourSpots": 14
  },
  {
    "official": "울산광역시 남구 달동",
    "restaurants": 1446,
    "vets": 6,
    "groomers": 24,
    "stays": 3
  },
  {
    "official": "울산광역시 남구 무거동",
    "restaurants": 773,
    "vets": 6,
    "groomers": 16,
    "stays": 1
  },
  {
    "official": "울산광역시 남구 삼산동",
    "restaurants": 827,
    "vets": 6,
    "groomers": 13,
    "stays": 8
  },
  {
    "official": "울산광역시 남구 신정동",
    "restaurants": 1128,
    "vets": 5,
    "groomers": 41,
    "stays": 1
  },
  {
    "official": "울산광역시 남구 옥동",
    "restaurants": 227,
    "vets": 2,
    "groomers": 3
  },
  {
    "official": "울산광역시 동구",
    "restaurants": 1941,
    "vets": 7,
    "groomers": 33,
    "stays": 4,
    "shelters": 1,
    "rescueDogs90": 10,
    "tourSpots": 16
  },
  {
    "official": "울산광역시 북구",
    "restaurants": 2324,
    "vets": 9,
    "groomers": 49,
    "stays": 8,
    "shelters": 3,
    "rescueDogs90": 21,
    "tourSpots": 12
  },
  {
    "official": "울산광역시 울주군",
    "restaurants": 3252,
    "vets": 24,
    "groomers": 37,
    "stays": 3,
    "shelters": 6,
    "rescueDogs90": 115,
    "tourSpots": 48
  },
  {
    "official": "울산광역시 울주군 범서읍",
    "restaurants": 533,
    "vets": 3,
    "groomers": 11
  },
  {
    "official": "울산광역시 울주군 언양읍",
    "restaurants": 437,
    "vets": 7,
    "groomers": 7,
    "shelters": 1
  },
  {
    "official": "울산광역시 중구",
    "restaurants": 2414,
    "vets": 13,
    "groomers": 42,
    "stays": 1,
    "shelters": 6,
    "rescueDogs90": 15,
    "tourSpots": 11
  },
  {
    "official": "인천광역시 강화군",
    "restaurants": 1584,
    "vets": 10,
    "groomers": 7,
    "stays": 4,
    "shelters": 2,
    "rescueDogs90": 106,
    "tourSpots": 33
  },
  {
    "official": "인천광역시 계양구",
    "restaurants": 2493,
    "vets": 22,
    "groomers": 53,
    "stays": 7,
    "shelters": 1,
    "rescueDogs90": 51,
    "tourSpots": 6
  },
  {
    "official": "인천광역시 계양구 계산동",
    "restaurants": 919,
    "vets": 5,
    "groomers": 12,
    "stays": 4
  },
  {
    "official": "인천광역시 계양구 작전동",
    "restaurants": 560,
    "vets": 10,
    "groomers": 19,
    "stays": 3
  },
  {
    "official": "인천광역시 남동구",
    "restaurants": 5027,
    "vets": 47,
    "groomers": 127,
    "stays": 13,
    "shelters": 4,
    "rescueDogs90": 57,
    "tourSpots": 5
  },
  {
    "official": "인천광역시 남동구 간석동",
    "restaurants": 895,
    "vets": 10,
    "groomers": 28,
    "stays": 2
  },
  {
    "official": "인천광역시 남동구 구월동",
    "restaurants": 1744,
    "vets": 14,
    "groomers": 26,
    "stays": 8
  },
  {
    "official": "인천광역시 남동구 논현동",
    "restaurants": 861,
    "vets": 9,
    "groomers": 25,
    "stays": 3
  },
  {
    "official": "인천광역시 남동구 만수동",
    "restaurants": 891,
    "vets": 11,
    "groomers": 30
  },
  {
    "official": "인천광역시 미추홀구",
    "restaurants": 4362,
    "vets": 27,
    "groomers": 107,
    "stays": 1,
    "rescueDogs90": 70,
    "tourSpots": 4
  },
  {
    "official": "인천광역시 미추홀구 도화동",
    "restaurants": 444,
    "vets": 1,
    "groomers": 10
  },
  {
    "official": "인천광역시 미추홀구 문학동",
    "restaurants": 142,
    "vets": 1,
    "groomers": 8
  },
  {
    "official": "인천광역시 미추홀구 숭의동",
    "restaurants": 371,
    "vets": 2,
    "groomers": 11
  },
  {
    "official": "인천광역시 미추홀구 용현동",
    "restaurants": 1197,
    "vets": 7,
    "groomers": 28
  },
  {
    "official": "인천광역시 미추홀구 주안동",
    "restaurants": 1730,
    "vets": 11,
    "groomers": 34,
    "stays": 1
  },
  {
    "official": "인천광역시 미추홀구 학익동",
    "restaurants": 373,
    "vets": 5,
    "groomers": 14
  },
  {
    "official": "인천광역시 부평구",
    "restaurants": 4511,
    "vets": 34,
    "groomers": 116,
    "stays": 3,
    "shelters": 4,
    "rescueDogs90": 35,
    "tourSpots": 10
  },
  {
    "official": "인천광역시 부평구 갈산동",
    "restaurants": 336,
    "vets": 3,
    "groomers": 13,
    "stays": 1
  },
  {
    "official": "인천광역시 부평구 산곡동",
    "restaurants": 286,
    "vets": 9,
    "groomers": 12
  },
  {
    "official": "인천광역시 부평구 삼산동",
    "restaurants": 415,
    "vets": 6,
    "groomers": 16
  },
  {
    "official": "인천광역시 서구",
    "shelters": 3,
    "tourSpots": 12
  },
  {
    "official": "인천광역시 연수구",
    "restaurants": 3967,
    "vets": 45,
    "groomers": 113,
    "stays": 4,
    "rescueDogs90": 16,
    "tourSpots": 9
  },
  {
    "official": "인천광역시 연수구 동춘동",
    "restaurants": 447,
    "vets": 4,
    "groomers": 10,
    "stays": 1
  },
  {
    "official": "인천광역시 연수구 선학동",
    "restaurants": 170,
    "vets": 1,
    "groomers": 3
  },
  {
    "official": "인천광역시 연수구 송도동",
    "restaurants": 1949,
    "vets": 30,
    "groomers": 64
  },
  {
    "official": "인천광역시 연수구 연수동",
    "restaurants": 741,
    "vets": 4,
    "groomers": 14
  },
  {
    "official": "인천광역시 연수구 옥련동",
    "restaurants": 404,
    "vets": 3,
    "groomers": 11,
    "stays": 1
  },
  {
    "official": "인천광역시 옹진군",
    "restaurants": 557,
    "stays": 4,
    "rescueDogs90": 16,
    "tourSpots": 24
  },
  {
    "official": "인천광역시 중구 인현동",
    "groomers": 1
  },
  {
    "official": "전라남도 강진군",
    "shelters": 1,
    "tourSpots": 29
  },
  {
    "official": "전라남도 고흥군",
    "shelters": 1,
    "tourSpots": 51
  },
  {
    "official": "전라남도 곡성군",
    "shelters": 1,
    "tourSpots": 25
  },
  {
    "official": "전라남도 광양시",
    "shelters": 1,
    "tourSpots": 14
  },
  {
    "official": "전라남도 구례군",
    "shelters": 2,
    "tourSpots": 31
  },
  {
    "official": "전라남도 나주시",
    "shelters": 2,
    "tourSpots": 32
  },
  {
    "official": "전라남도 담양군",
    "shelters": 1,
    "tourSpots": 23
  },
  {
    "official": "전라남도 목포시",
    "tourSpots": 11
  },
  {
    "official": "전라남도 무안군",
    "shelters": 1,
    "tourSpots": 29
  },
  {
    "official": "전라남도 무안군 삼향읍",
    "shelters": 2
  },
  {
    "official": "전라남도 보성군",
    "shelters": 1,
    "tourSpots": 26
  },
  {
    "official": "전라남도 순천시",
    "shelters": 2,
    "tourSpots": 22
  },
  {
    "official": "전라남도 신안군",
    "tourSpots": 48
  },
  {
    "official": "전라남도 여수시",
    "tourSpots": 63
  },
  {
    "official": "전라남도 영광군",
    "shelters": 1,
    "tourSpots": 27
  },
  {
    "official": "전라남도 영암군",
    "shelters": 1,
    "tourSpots": 21
  },
  {
    "official": "전라남도 완도군",
    "shelters": 1,
    "tourSpots": 31
  },
  {
    "official": "전라남도 장성군",
    "shelters": 1,
    "tourSpots": 15
  },
  {
    "official": "전라남도 장흥군",
    "shelters": 1,
    "tourSpots": 24
  },
  {
    "official": "전라남도 진도군",
    "shelters": 1,
    "tourSpots": 38
  },
  {
    "official": "전라남도 함평군",
    "shelters": 1,
    "tourSpots": 17
  },
  {
    "official": "전라남도 해남군",
    "shelters": 1,
    "tourSpots": 44
  },
  {
    "official": "전라남도 화순군",
    "shelters": 1,
    "tourSpots": 39
  },
  {
    "official": "전북특별자치도 고창군",
    "restaurants": 762,
    "vets": 13,
    "groomers": 1,
    "stays": 1,
    "rescueDogs90": 87,
    "tourSpots": 55
  },
  {
    "official": "전북특별자치도 군산시",
    "restaurants": 4452,
    "vets": 19,
    "groomers": 54,
    "stays": 19,
    "shelters": 1,
    "rescueDogs90": 121,
    "tourSpots": 53
  },
  {
    "official": "전북특별자치도 군산시 나운동",
    "restaurants": 748,
    "vets": 2,
    "groomers": 8,
    "stays": 3
  },
  {
    "official": "전북특별자치도 김제시",
    "restaurants": 1075,
    "vets": 19,
    "groomers": 5,
    "stays": 1,
    "rescueDogs90": 92,
    "tourSpots": 45
  },
  {
    "official": "전북특별자치도 남원시",
    "restaurants": 1266,
    "vets": 10,
    "groomers": 7,
    "stays": 9,
    "shelters": 3,
    "rescueDogs90": 100,
    "tourSpots": 55
  },
  {
    "official": "전북특별자치도 무주군",
    "restaurants": 489,
    "vets": 2,
    "groomers": 2,
    "stays": 6,
    "shelters": 1,
    "rescueDogs90": 6,
    "tourSpots": 28
  },
  {
    "official": "전북특별자치도 부안군",
    "restaurants": 910,
    "vets": 11,
    "groomers": 4,
    "stays": 6,
    "shelters": 1,
    "rescueDogs90": 129,
    "tourSpots": 41
  },
  {
    "official": "전북특별자치도 순창군",
    "restaurants": 350,
    "vets": 8,
    "groomers": 1,
    "rescueDogs90": 3,
    "tourSpots": 29
  },
  {
    "official": "전북특별자치도 완주군",
    "restaurants": 1562,
    "vets": 13,
    "groomers": 8,
    "stays": 2,
    "shelters": 1,
    "rescueDogs90": 54,
    "tourSpots": 51
  },
  {
    "official": "전북특별자치도 익산시",
    "restaurants": 3488,
    "vets": 26,
    "groomers": 45,
    "stays": 3,
    "shelters": 1,
    "rescueDogs90": 249,
    "tourSpots": 62
  },
  {
    "official": "전북특별자치도 익산시 영등동",
    "restaurants": 597,
    "vets": 2,
    "groomers": 6,
    "stays": 1
  },
  {
    "official": "전북특별자치도 임실군",
    "restaurants": 357,
    "vets": 7,
    "rescueDogs90": 52,
    "tourSpots": 45
  },
  {
    "official": "전북특별자치도 장수군",
    "restaurants": 263,
    "vets": 8,
    "shelters": 1,
    "rescueDogs90": 5,
    "tourSpots": 41
  },
  {
    "official": "전북특별자치도 전주시",
    "restaurants": 8466,
    "vets": 49,
    "groomers": 152,
    "stays": 55,
    "shelters": 2,
    "rescueDogs90": 153,
    "tourSpots": 44
  },
  {
    "official": "전북특별자치도 전주시 덕진구 송천동",
    "restaurants": 785,
    "vets": 6,
    "groomers": 31
  },
  {
    "official": "전북특별자치도 전주시 완산구 서신동",
    "restaurants": 518,
    "vets": 3,
    "groomers": 8
  },
  {
    "official": "전북특별자치도 전주시 완산구 효자동",
    "restaurants": 1337,
    "vets": 9,
    "groomers": 39,
    "stays": 1
  },
  {
    "official": "전북특별자치도 정읍시",
    "restaurants": 1383,
    "vets": 27,
    "groomers": 16,
    "stays": 2,
    "shelters": 1,
    "rescueDogs90": 117,
    "tourSpots": 52
  },
  {
    "official": "전북특별자치도 진안군",
    "restaurants": 304,
    "vets": 7,
    "shelters": 1,
    "rescueDogs90": 16,
    "tourSpots": 30
  },
  {
    "official": "제주특별자치도 서귀포시",
    "restaurants": 4869,
    "vets": 22,
    "groomers": 29,
    "stays": 202,
    "shelters": 1,
    "tourSpots": 140
  },
  {
    "official": "제주특별자치도 서귀포시 성산읍",
    "restaurants": 591,
    "vets": 1,
    "groomers": 1,
    "stays": 24
  },
  {
    "official": "제주특별자치도 서귀포시 중문동",
    "restaurants": 241,
    "vets": 1,
    "groomers": 3,
    "stays": 9
  },
  {
    "official": "제주특별자치도 제주시",
    "restaurants": 10836,
    "vets": 93,
    "groomers": 113,
    "stays": 220,
    "shelters": 3,
    "tourSpots": 168
  },
  {
    "official": "제주특별자치도 제주시 노형동",
    "restaurants": 990,
    "vets": 9,
    "groomers": 18,
    "stays": 11
  },
  {
    "official": "제주특별자치도 제주시 애월읍",
    "restaurants": 878,
    "vets": 9,
    "groomers": 10,
    "stays": 47,
    "shelters": 1
  },
  {
    "official": "제주특별자치도 제주시 연동",
    "restaurants": 1351,
    "vets": 10,
    "groomers": 15,
    "stays": 36
  },
  {
    "official": "제주특별자치도 제주시 한림읍",
    "restaurants": 782,
    "vets": 14,
    "groomers": 4,
    "stays": 33
  },
  {
    "official": "충청남도 계룡시",
    "restaurants": 454,
    "vets": 4,
    "groomers": 7,
    "shelters": 1,
    "rescueDogs90": 7,
    "tourSpots": 8
  },
  {
    "official": "충청남도 공주시",
    "restaurants": 2013,
    "vets": 23,
    "groomers": 12,
    "stays": 3,
    "shelters": 1,
    "rescueDogs90": 68,
    "tourSpots": 45
  },
  {
    "official": "충청남도 금산군",
    "restaurants": 868,
    "vets": 6,
    "groomers": 9,
    "shelters": 1,
    "rescueDogs90": 31,
    "tourSpots": 26
  },
  {
    "official": "충청남도 논산시",
    "restaurants": 1847,
    "vets": 19,
    "groomers": 17,
    "shelters": 1,
    "rescueDogs90": 120,
    "tourSpots": 42
  },
  {
    "official": "충청남도 당진시",
    "restaurants": 2913,
    "vets": 29,
    "groomers": 40,
    "stays": 2,
    "shelters": 1,
    "rescueDogs90": 120,
    "tourSpots": 32
  },
  {
    "official": "충청남도 보령시",
    "restaurants": 1919,
    "vets": 11,
    "groomers": 17,
    "stays": 7,
    "shelters": 2,
    "rescueDogs90": 48,
    "tourSpots": 56
  },
  {
    "official": "충청남도 부여군",
    "restaurants": 823,
    "vets": 14,
    "groomers": 6,
    "stays": 1,
    "shelters": 1,
    "rescueDogs90": 101,
    "tourSpots": 57
  },
  {
    "official": "충청남도 서산시",
    "restaurants": 2724,
    "vets": 21,
    "groomers": 35,
    "stays": 3,
    "shelters": 1,
    "rescueDogs90": 135,
    "tourSpots": 47
  },
  {
    "official": "충청남도 서천군",
    "restaurants": 744,
    "vets": 5,
    "groomers": 4,
    "rescueDogs90": 19,
    "tourSpots": 38
  },
  {
    "official": "충청남도 아산시",
    "restaurants": 4866,
    "vets": 35,
    "groomers": 68,
    "stays": 5,
    "shelters": 1,
    "rescueDogs90": 107,
    "tourSpots": 45
  },
  {
    "official": "충청남도 아산시 배방읍",
    "restaurants": 903,
    "vets": 7,
    "groomers": 17
  },
  {
    "official": "충청남도 예산군",
    "restaurants": 1336,
    "vets": 21,
    "groomers": 13,
    "stays": 3,
    "shelters": 1,
    "rescueDogs90": 59,
    "tourSpots": 24
  },
  {
    "official": "충청남도 천안시",
    "restaurants": 8882,
    "vets": 69,
    "groomers": 183,
    "stays": 7,
    "shelters": 1,
    "rescueDogs90": 189,
    "tourSpots": 45
  },
  {
    "official": "충청남도 천안시 서북구 두정동",
    "restaurants": 917,
    "vets": 6,
    "groomers": 31
  },
  {
    "official": "충청남도 천안시 서북구 불당동",
    "restaurants": 950,
    "vets": 8,
    "groomers": 23,
    "stays": 1
  },
  {
    "official": "충청남도 천안시 서북구 성정동",
    "restaurants": 925,
    "vets": 5,
    "groomers": 24,
    "stays": 3
  },
  {
    "official": "충청남도 천안시 서북구 쌍용동",
    "restaurants": 815,
    "vets": 7,
    "groomers": 18
  },
  {
    "official": "충청남도 청양군",
    "restaurants": 479,
    "vets": 9,
    "groomers": 1,
    "stays": 1,
    "shelters": 1,
    "rescueDogs90": 13,
    "tourSpots": 25
  },
  {
    "official": "충청남도 태안군",
    "restaurants": 1286,
    "vets": 7,
    "groomers": 8,
    "stays": 9,
    "shelters": 2,
    "rescueDogs90": 79,
    "tourSpots": 78
  },
  {
    "official": "충청남도 홍성군",
    "restaurants": 1666,
    "vets": 25,
    "groomers": 16,
    "stays": 2,
    "shelters": 1,
    "rescueDogs90": 52,
    "tourSpots": 28
  },
  {
    "official": "충청북도 괴산군",
    "restaurants": 664,
    "vets": 7,
    "groomers": 2,
    "stays": 1,
    "rescueDogs90": 40,
    "tourSpots": 71
  },
  {
    "official": "충청북도 단양군",
    "restaurants": 717,
    "vets": 1,
    "groomers": 2,
    "stays": 2,
    "shelters": 1,
    "rescueDogs90": 6,
    "tourSpots": 43
  },
  {
    "official": "충청북도 보은군",
    "restaurants": 566,
    "vets": 10,
    "groomers": 1,
    "stays": 1,
    "rescueDogs90": 13,
    "tourSpots": 25
  },
  {
    "official": "충청북도 영동군",
    "restaurants": 732,
    "vets": 5,
    "groomers": 5,
    "stays": 1,
    "shelters": 1,
    "rescueDogs90": 40,
    "tourSpots": 32
  },
  {
    "official": "충청북도 옥천군",
    "restaurants": 810,
    "vets": 8,
    "groomers": 10,
    "shelters": 1,
    "rescueDogs90": 78,
    "tourSpots": 29
  },
  {
    "official": "충청북도 음성군",
    "restaurants": 2244,
    "vets": 14,
    "groomers": 13,
    "stays": 1,
    "shelters": 1,
    "rescueDogs90": 109,
    "tourSpots": 32
  },
  {
    "official": "충청북도 제천시",
    "restaurants": 2334,
    "vets": 11,
    "groomers": 25,
    "stays": 9,
    "shelters": 1,
    "rescueDogs90": 23,
    "tourSpots": 62
  },
  {
    "official": "충청북도 증평군",
    "restaurants": 616,
    "vets": 5,
    "groomers": 6,
    "stays": 1,
    "shelters": 3,
    "rescueDogs90": 13,
    "tourSpots": 9
  },
  {
    "official": "충청북도 진천군",
    "restaurants": 1573,
    "vets": 12,
    "groomers": 15,
    "rescueDogs90": 46,
    "tourSpots": 35
  },
  {
    "official": "충청북도 청주시",
    "restaurants": 11361,
    "vets": 90,
    "groomers": 212,
    "stays": 6,
    "shelters": 1,
    "rescueDogs90": 208,
    "tourSpots": 63
  },
  {
    "official": "충청북도 청주시 상당구 용암동",
    "restaurants": 818,
    "vets": 6,
    "groomers": 24
  },
  {
    "official": "충청북도 청주시 청원구 오창읍",
    "restaurants": 839,
    "vets": 9,
    "groomers": 16
  },
  {
    "official": "충청북도 청주시 청원구 율량동",
    "restaurants": 593,
    "vets": 5,
    "groomers": 13,
    "stays": 1
  },
  {
    "official": "충청북도 청주시 흥덕구 가경동",
    "restaurants": 608,
    "vets": 6,
    "groomers": 14
  },
  {
    "official": "충청북도 청주시 흥덕구 복대동",
    "restaurants": 1000,
    "vets": 6,
    "groomers": 18
  },
  {
    "official": "충청북도 청주시 흥덕구 오송읍",
    "restaurants": 575,
    "vets": 4,
    "groomers": 9
  },
  {
    "official": "충청북도 충주시",
    "restaurants": 3720,
    "vets": 20,
    "groomers": 55,
    "stays": 14,
    "shelters": 1,
    "rescueDogs90": 57,
    "tourSpots": 99
  }
];
