import sanitizeHtml from "sanitize-html";

export function cleanHtml(html: string): string {
  return sanitizeHtml(html, {
    allowedTags: [
      "h2",
      "h3",
      "p",
      "br",
      "strong",
      "em",
      "b",
      "i",
      "ul",
      "ol",
      "li",
      "blockquote",
      "cite",
      "a",
      "img",
      "figure",
      "figcaption",
      "span",
      "div",
      "section",
      "article",
      "table",
      "thead",
      "tbody",
      "tr",
      "th",
      "td",
      "dl",
      "dt",
      "dd",
    ],
    allowedAttributes: {
      a: ["href", "target", "rel"],
      img: ["src", "alt", "width", "height", "loading", "decoding"],
      span: ["class"],
      blockquote: ["class"],
      div: ["class", "data-block", "data-mw-slot"],
      section: ["class", "data-facts"],
      article: ["class", "data-animal-id"],
      figure: ["class"],
      table: ["class"],
      th: ["scope"],
      td: ["class"],
      p: ["class"],
    },
    allowedSchemes: ["http", "https", "mailto"],
  });
}

/**
 * Strip AI-invented images from Writer HTML while keeping Verified media
 * (figure/img from code renderers) and structural wrappers.
 */
export function stripGeneratedImages(html: string): string {
  return sanitizeHtml(html, {
    allowedTags: [
      "h2",
      "h3",
      "p",
      "br",
      "strong",
      "em",
      "b",
      "i",
      "ul",
      "ol",
      "li",
      "blockquote",
      "cite",
      "a",
      "span",
      "section",
      "article",
      "div",
      "figure",
      "figcaption",
      "img",
      "table",
      "thead",
      "tbody",
      "tr",
      "th",
      "td",
      "dl",
      "dt",
      "dd",
    ],
    allowedAttributes: {
      a: ["href", "target", "rel"],
      img: ["src", "alt", "width", "height", "loading", "decoding"],
      span: ["class"],
      blockquote: ["class"],
      section: ["class", "data-facts"],
      article: ["class", "data-animal-id"],
      div: ["class", "data-block"],
      figure: ["class"],
      table: ["class"],
      th: ["scope"],
      td: ["class"],
      p: ["class"],
    },
    allowedSchemes: ["http", "https", "mailto"],
  });
}
